-- phpMyAdmin SQL Dump
-- version 4.9.0.1
-- https://www.phpmyadmin.net/
--
-- Host: sql313.epizy.com
-- Generation Time: Apr 12, 2023 at 05:00 AM
-- Server version: 10.4.17-MariaDB
-- PHP Version: 7.2.22

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `epiz_33741504_urc_database`
--

-- --------------------------------------------------------

--
-- Table structure for table `pubnew`
--

CREATE TABLE `pubnew` (
  `id` int(11) DEFAULT NULL,
  `name` varchar(255) NOT NULL DEFAULT 'Dr.W.M.G.M.B.Bowatte',
  `faculty` varchar(255) NOT NULL DEFAULT 'Allied Health Sciences',
  `publication` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `pubnew`
--

INSERT INTO `pubnew` (`id`, `name`, `faculty`, `publication`) VALUES
(1, 'Prof.J.B.Ekanayake', 'Engineering', 'Ramitha Dissanayake, Akila Wijethunge, Janaka Wijayakulasooriya and Janaka Ekanayake, “Optimizing PV-Hosting Capacity with the Integrated Employment of Dynamic Line Rating and Voltage Regulation”, Energies (IF: 3.252), 2022, 15, 8537. https://doi.org/10.3390/en1522853.'),
(2, 'Prof.J.B.Ekanayake', 'Engineering', 'Gihan Jayatilaka, Jameel Hassan, Suren Sritharan, Janith Bandara Senanayaka, Harshana Weligampola, Roshan Godaliyadda, Parakrama Ekanayake, Vijitha Herath, Janaka Ekanayake and Samath Dharmaratne, “Holistic Interpretation of Public Scenes Using Computer Vision and Temporal Graphs to Identify Social Distancing Violations”, Applied Sciences (IF: 2.838), 2022, Vol 12, 8428, https://doi.org/10.3390/app12178428.'),
(3, 'Prof.J.B.Ekanayake', 'Engineering', 'Misbah Abdelrahim, Gamal Alkawsi, Ammar Ahmed Alkahtani, Ali M. W. Alhasan,Mohammad Khudari, Mohd Rizuan Abdul Kadir, Janaka Ekanayake and Sieh Kiong Tiong, “Techno-Economic Analysis of aWind-Energy-Based Charging Station for Electric Vehicles in High-Rise Buildings in Malaysia”, Energies (IF: 3.252), 2022, 15, 5412. https://doi.org/10.3390/en15155412.'),
(4, 'Prof.J.B.Ekanayake', 'Engineering', 'G Ilangarathna, H Weligampola, Y Ranasinghe, E Attygalla, R Godaliyaddha, V Herath, P Ekanayake, SY Ekanayake, M Pinnawela, S Dharmaratne, G Tilakaratne and J Ekanayake, “Artificial intelligence framework for threat assessment and containment for covid-19 and future epidemics while mitigating the socioeconomic impact to women, children, and underprivileged groups”, Journal of National Science Foundation Sri Lanka (IF: 0.682), 2022 50 (Special), pp 81 – 92.'),
(5, 'Prof.J.B.Ekanayake', 'Engineering', 'Krishnakumar R. Vasudevan; Vigna K. Ramachandaramurthy; Gomathi Venugopal; Josep M. Guerrero; Janaka B. Ekanayake; Sieh Kiong Tiong, “Variable speed pico hydel energy storage with synchronverter control to emulate virtual inertia in autonomous microgrids”, IEEE Systems Journal (IF: 2.702), Vol. 16, No. 1, March 2022, DOI: 10.1109/JSYST.2021.3053358.'),
(6, 'Prof.J.B.Ekanayake', 'Engineering', 'Eshan Karunarathne, Akila Wijethunge and Janaka Ekanayake, “Enhancing PV Hosting Capacity Using Voltage Control and Employing Dynamic Line Rating”, Energies (IF: 2.702), 2022, 15(1), 134.'),
(7, 'Prof.J.B.Ekanayake', 'Engineering', 'Eshan Karunarathne, Anjana Wijesekera, Lilantha Samaranayake*, Prabath Binduhewa, and Janaka Ekanayake, “On the Implementation of Hybrid Energy Storage for Range and Battery Life Extension of an Electrified Tuk-Tuk”, Journal of Energy Storage (IF: 6.583), Volume 46, February 2022.'),
(8, 'Prof.J.B.Ekanayake', 'Engineering', 'Dilan I. Manamperi, Janaka B. Ekanayake, “Performance comparison of optimum power flow based on the sequential second-order cone programming in unbalanced low voltage distribution networks with distributed generators\", International Transactions on Electrical Energy Systems (IF: 1.692), Volume31, Issue12, December 2021.'),
(9, 'Prof.J.B.Ekanayake', 'Engineering', 'A.S. Jameel Hassan, Umar Marikkar, G.W. Kasun Prabhath, Aranee Balachandran, W.G. Chaminda Bandara, Parakrama B Ekanayake, Roshan I Godaliyadda, Janaka B Ekanayake, “A Sensitivity Matrix Approach Using Two-Stage Optimization for Voltage Regulation of LV Networks with High PV Penetration”, Special issue on “Smart Grids and Microgrids”, Energies (IF: 3.004), Vol 14, Issue 20, 2021.'),
(10, 'Prof.J.B.Ekanayake', 'Engineering', 'Charithri Yapa, Chamithade Alwis, Madhusanka Liyanage, Janaka Ekanayake, “Survey on blockchain for future smart grids: Technical aspects, applications, integration challenges and future research”, Energy Reports (IF 6.870), Volume 7, November 2021, Pages 6530-6564.'),
(11, 'Prof.J.B.Ekanayake', 'Engineering', 'Ameen Sarhan, Vigna K. Ramachandaramurthy, Tiong Seih Kiong, Janaka Ekanayake, “Impact of techno-economic parameters on the power systems model with high share of renewable energy and energy storage”, International Transactions on Electrical Energy Systems (IF: 1.692), DOI: 10.1002/2050-7038.13073 (online)'),
(12, 'Prof.J.B.Ekanayake', 'Engineering', 'Ameen Sarhan, Vigna K. Ramachandaramurthy, Tiong Sieh Kiong, Janaka Ekanayake, “Definitions and dimensions for electricity security assessment: A Review”, Sustainable Energy Technologies and Assessments (IF: 7.632), Vol 48, Sep 2021 101626.'),
(13, 'Prof.J.B.Ekanayake', 'Engineering', 'Lasanthika H. Dissawa, Roshan I. Godaliyadda, Parakrama B. Ekanayake, Ashish P. Agalgaonkar, Duane Robinson, Janaka B. Ekanayake, and Sarath Perera, “Sky Image-Based Localized, Short-Term Solar Irradiance Forecasting for Multiple PV Sites via Cloud Motion Tracking”, International Journal of Photoenergy (IF: 2.113), Volume 2021, Article ID 9973010, 27 pages.'),
(14, 'Prof.J.B.Ekanayake', 'Engineering', 'Dilini Almeida, Jagadeesh Pasupuleti, Janaka Ekanayake, “Comparison of Reactive Power Control Techniques for Solar PV Inverters to Mitigate Voltage Rise in Low Voltage Grids”, Electronics (IF: 2.412) Vol 10, No, 13, 1569, 2021'),
(15, 'Prof.J.B.Ekanayake', 'Engineering', 'Aidha Muhammad Ajmal, Vigna K. Ramachandaramurthy, Amirreza Naderipour, Janaka B. Ekanayake, “Comparative analysis of two-step GA-based PV array reconfiguration technique and other reconfiguration techniques”, Energy Conversion and Management (IF: 8.208), 230, 2021.'),
(16, 'Prof.J.B.Ekanayake', 'Engineering', 'Eshan Karunarathne, Jagadeesh Pasupuleti, Janaka Ekanayake and Dilini Almeida, “The Optimal Placement and Sizing of Distributed Generation in an Active Distribution Network with Several Soft Open Points”, Energies (IF: 3.004), 2021, 14(4), 1084.'),
(17, 'Prof.J.B.Ekanayake', 'Engineering', 'Aidha Muhammad Ajmal, Vigna K. Ramachandaramurthy, Anuradha Tomar, Janaka B. Ekanayake, “Optimal dynamic reconfiguration of large-scale PV plant under partial\r\nshading conditions based on two reconfigurable stages”, International Transactions on Electrical Energy Systems (IF: 1.692) (Accepted)\r\n'),
(18, 'Prof.J.B.Ekanayake', 'Engineering', 'Eshan Karunarathne, Jagadeesh Pasupuleti, Janaka Ekanayake and Dilini Almeida, “Optimal Placement and Sizing of DGs in Distribution Networks Using MLPSO Algorithm”, Energies (IF: 2.702), Energies 2020, 13, 6185; doi:10.3390/en13236185.'),
(19, 'Prof.J.B.Ekanayake', 'Engineering', 'Wele Gedara Chaminda Bandara, Dilini Almeida, G.M.R.I. Godaliyadda, Mervyn Parakrama Ekanayake, Janaka Bandara Ekanayake, “A Complete State Estimation Algorithm for a Three-Phase Four-Wire Low Voltage Distribution System with High Penetration of Solar PV”, International Journal of Electrical Power and Energy Systems (IF: 3.588), Volume 124, January 2021, 106332.'),
(20, 'Prof.J.B.Ekanayake', 'Engineering', 'Krishnakumar R. Vasudevan, Vigna K. Ramachandaramurthy, Gomathi Venugopal, J. B. Ekanayake, S.K. Tiong, “Hierarchical frequency control framework for a remote microgrid with pico hydel energy storage and wind turbine”, Electrical Power and Energy Systems (IF: 5.659), Vol 127, 2021, 106666'),
(21, 'Prof.J.B.Ekanayake', 'Engineering', 'W.G. Chaminda Bandara, G.M.R.I. Godaliyadda, M.P.B. Ekanayake, J.B. Ekanayake, “Coordinated PV re-phasing: a novel method to maximize renewable energy integration in LV networks by mitigating network unbalances”, Applied Energy (IF: 8.848), Volume 280, 15 December 2020.'),
(22, 'Prof.J.B.Ekanayake', 'Engineering', 'Ling Ai Wong, Vigna K. Ramachandaramurthy, Sara L. Walker, and Janaka B. Ekanayake, “Optimal Placement and Sizing of Battery Energy Storage System Considering the Duck Curve Phenomenon”, IEEE Access (IF: 3.745), Volume 8, Nov 2020, pp 197236 – 197248.'),
(23, 'Prof.J.B.Ekanayake', 'Engineering', 'Norman, Fuad, Ammar Ahmed Alkahtani, Vassilios Agelidis, Kiong Sieh Tiong, Gamal Alkawsi, and Janaka Ekanayake, “Wind -Energy -Powered Electric Vehicle Charging Stations: Resource Availability Data Analysis”, Applied Science (IF: 2.217), 2020, 10, 5654; doi:10.3390/app10165654'),
(24, 'Prof.J.B.Ekanayake', 'Engineering', 'F. M. Noman, G. A. Alkawsi, D. Abbas, A. A. Alkahtani, S. K. Tiong and J. Ekanayake, \"Comprehensive Review of Wind Energy in Malaysia: Past, Present, and Future Research Trends,\" in IEEE Access (IF: 3.745), vol. 8, pp. 124526-124543, 2020, doi: 10.1109/ACCESS.2020.3006134.'),
(25, 'Prof.J.B.Ekanayake', 'Engineering', 'Dilini Almeida, Sathsara Abeysinghe, Mervyn Parakrama Ekanayake, Roshan Indika Godaliyadda, Janaka Ekanayake, Jagadeesh Pasupuleti, “Generalized approach to assess and characterise the impact of solar PV on LV networks”, International Journal of Electrical Power and Energy Systems (IF: 3.588), Volume 121, October 2020'),
(26, 'Prof.J.B.Ekanayake', 'Engineering', 'Krishnakumar R. Vasudevan, Vigna K. Ramachandaramurthy, Gomathi Venugopal, J. B. Ekanayake, S.K. Tiong, “Variable speed pumped hydro storage: A review of converters, controls and energy management strategies”, Renewable and Sustainable Energy Reviews (IF:16.799), Vol 135, Aug 2020, 110156.'),
(27, 'Prof.J.B.Ekanayake', 'Engineering', 'Aidha Muhammad Ajmala, Thanikanti Sudhakar Babua, Vigna K. Ramachandaramurthya, Dalia. Yousrib, Janaka B. Ekanayake, “Static and dynamic reconfiguration approaches for mitigation of partial shading influence in photovoltaic arrays”, Sustainable Energy Technologies and Assessments (IF: 3.427), Volume 40, August 2020, 100738.'),
(28, 'Prof.J.B.Ekanayake', 'Engineering', 'Phung Dang Huy, Vigna K. Ramachandaramurthy, Jia Ying Yong, Kang Miao Tan, Janaka B. Ekanayake, “Optimal placement, sizing and power factor of distributed generation: A comprehensive study spanning from the planning stage to the operation stage”, Energy (IF: 6.082), Volume 195(15), March 2020, Article 117011.'),
(29, 'Prof.J.B.Ekanayake', 'Engineering', 'Gayanthi A. Ilangarathna, Yasiru Ranasinghe, Harshana Weligampola, Erandi Attygalla, Janaka Ekanayake, Sakunthala Yatigammana, Mallika Pinnawala, Roshan Godaliyadda, Vijitha Herath, Parakrama Ekanayake, Ganga Thilakaratne and Samath Dharmarathne, “A Comprehensive Overview of Education during Three COVID-19 Pandemic Periods: Impact on Engineering Students in Sri Lanka”, MDPI Education Science (CiteScore: 2.1), 2022, 12, 197. https://doi.org/10.3390/educsci12030197'),
(30, 'Prof.J.B.Ekanayake', 'Engineering', 'Dallatu Abbas U, SK Tiong, Ammar Ahmed Alkahtani, CP Chen, Gamal Alkawsi, and Janaka Ekanayake, “Power Curve Evaluation of Micro-Scale Turbines for Harvesting Wind Energy in Malaysia”, Applied Mathematics & Information Sciences (CiteScore: 1.4), 15, No. 1, 59-71, 2021.'),
(31, 'Prof.J.B.Ekanayake', 'Engineering', 'Eshan Karunarathne, Jagadeesh Pasupuleti, Janaka Ekanayake, Dilini Almeida, “Network loss reduction and voltage improvement by optimal placement and sizing of distributed generators with active and reactive power injection using fine-tuned PSO”, Indonesian Journal of Electrical Engineering and Computer Science (CiteScore: 1.4), Vol. 21, No. 2, February 2021, pp. 647-656.'),
(32, 'Prof.J.B.Ekanayake', 'Engineering', 'Gamal  Abdulnaser Alkawsi, Norashikin Ali, Abdulsalam Salihu Mustafa, Yahia Baashar, Hitham Alhussian, Ammar Alkahtani, Sieh Kiong Tiong, Janaka Ekanayake, A hybrid SEM-neural network method for identifying acceptance factors of the smart meters in Malaysia: Challenges perspective, Alexandria Engineering Journal (CiteScore: 6.5), Volume 60, Issue 1, February 2021, Pages 227-240.'),
(33, 'Prof.J.B.Ekanayake', 'Engineering', 'Dilini Almeida, Jagadeesh Pasupuleti, Janaka Ekanayake, “Performance evaluation of PV penetration at different locations in a LV distribution network connected with an off-load tap changing transformer”, Indonesian Journal of Electrical Engineering and Computer Science (CiteScore: 1.4), Vol. 21, No. 2, February 2021, pp. 987~993.'),
(34, 'Prof.J.B.Ekanayake', 'Engineering', 'Al Eli Elixie, Ammar Ahmed Alkahtani, Gamal Alkawsi, Siti Fatihah Salle, Yousef Fazea, Janaka Ekanayake, Non-Intrusive Electrical Load Monitoring and Identification: Approaches, Tools and a Case Study, Applied Mathematics & Information Sciences (CiteScore: 1.4), Vol 14, No 6, 1017-1027, Nov 2020.'),
(35, 'Prof.J.B.Ekanayake', 'Engineering', 'Fuad Noman, GamalAlkawsi, Ammar Ahmed Alkahtani, Ali Q.Al-Shetwi, Sieh Kiong Tiong, Nasser Alalwan, Janaka Ekanayake, Ahmed Ibrahim Alzahrani,, “Multistep short-term wind speed prediction using nonlinear auto-regressive neural network with exogenous variable selection”, Alexandria Engineering Journal (CiteScore: 6.5), Available online 5 Nov 2020, https://doi.org/10.1016/j.aej.2020.10.045.'),
(36, 'Prof.J.B.Ekanayake', 'Engineering', 'Eshan Karunarathne, Jagadeesh Pasupuleti, Janaka Ekanayake, Dilini Almeida, “Comprehensive learning particle swarm optimization for sizing and placement of distributed generation for network loss reduction”, Indonesian Journal of Electrical Engineering and Computer Science (CiteScore: 1.4), Vol. 20, No. 1, October 2020, pp. 16-23.'),
(37, 'Prof.J.B.Ekanayake', 'Engineering', 'Dilini Almeida, Jagadeesh Pasupuleti, Janaka Ekanayake, Eshan Karunarathne, “Mitigation of overvoltage due to high penetration of solar photovoltaics using smart inverters volt/var control”, Indonesian Journal of Electrical Engineering and Computer Science (CiteScore: 1.4), Vol. 19, No. 3, September 2020, pp. 1259~1266.'),
(38, 'Prof.J.B.Ekanayake', 'Engineering', 'Ying Ying Koay, Jian Ding Tan, Siaw Paw Koh, Kok Hen Chong, Sieh Kiong Tiong, Janaka Ekanayake, “Optimization of wind energy conversion systems – an artificial intelligent approach”, International Journal of Power Electronics and Drive Systems (CiteScore: 1.49), Vol 11, No 2, June 2020, pp 1040-1046.'),
(39, 'Prof.M.A.R.M.Fernando ', 'Engineering', 'Venkatesh Srinivasan, M.A.R.M. Fernando, Sarath Kumara, Selvaraj Thirumalini, and Vernon Cooray “Modeling and Assessment of Lightning Hazards to Humans in Heritage Monuments in India and Sri Lanka “, IEEE ACCESS, Vol. 8, pp. 228032- 228048, 2020'),
(40, 'Prof.M.A.R.M.Fernando', 'Engineering', 'J.R.S.S. Kumara, M.A.R.M. Fernando, G.A.T.N. Aravinda, D.S. Daulagala, M.A.A.P. Bandara, H.P.I.P. Nandasena and G.A. Jayantha, “Condition Assessment of 132/220 kV Oil-Paper Current Transformers in Sri Lanka, IEEE Electrical Insulation Magazine, Vol. 6, No. 6, pp. 21-30, 2020.'),
(41, 'Prof.M.A.R.M.Fernando', 'Engineering', 'J.R.S.S. Kumara and M.A.R.M. Fernando, “Performance of Outdoor Insulators in Tropical Conditions of Sri Lanka”, IEEE Electrical Insulation Magazine, Vol 36. No. 4, pp. 26-5, July/August 2020'),
(42, 'Prof.M.A.R.M.Fernando', 'Engineering', 'Selvaraj Thirumalini, Venkatesh Srinivasan, Simona Raneri, M.A.R.M. Fernando, Kunal Kakria, Simon Jayasingh, “ Response of organic lime mortars to thermal and electrical shocks due to lightning strikes“, MDPI Sustainability Journal, September 2020, Vol 12, Issue 17, 7182.'),
(43, 'Prof.M.A.R.M.Fernando', 'Engineering', 'T.Herath, J.R.S.S. Kumara, K. Bandara, J. Wijayaklasooriya, M.A.R.M. Fernando and G.A.Jayantha, “Field verification of a Simple Partial Discharge Method for Generator Applications”, IET Science, Measurements & Technology 14 (7), September 2020'),
(44, 'Prof.M.A.R.M.Fernando', 'Engineering', 'Sarath Kumara, Shanika Matharage, Kapila Bandara, Prasanna Wickramasuriya, Fairouz Yousuf, Chandima Ekanayake, M.A.R.M. Fernando, Zhongdong Wang, Stanislaw Gubanski, “Frequency Domain Measurements for Diagnosis of Power Transformers: Experiences from Australia, Malaysia, Sri Lanka and UK”, Cigre Science and Engineering Journal, October 2021'),
(45, 'Prof.R.G.Ragel', 'Engineering', 'Senanayake, A., Gamaarachchi, H., Herath, D. et al. DeepSelectNet: deep neural network based selective sequencing for oxford nanopore sequencing. BMC Bioinformatics 24, 31 (2023). https://doi.org/10.1186/s12859-023-05151-0'),
(46, 'Prof.R.G.Ragel', 'Engineering', 'K. Liyanage, H. Gamaarachchi, R. Ragel and S. Parameswaran, \"Cross Layer Design Using HW/SW Co-Design and HLS to Accelerate Chaining in Genomic Analysis,\" in IEEE Transactions on Computer-Aided Design of Integrated Circuits and Systems, doi: 10.1109/TCAD.2023.3236559.'),
(47, 'Prof.R.G.Ragel', 'Engineering', 'Jiffriya Mohamed Abdul Cader, Akmal Jahan Mohamed Abdul Cader, Hasindu Gamaarachchi, and Roshan G. Ragel, Optimisation of plagiarism detection using vector space model on CUDA architecture, International Journal of Innovative Computing and Applications 2022 13:4, 232-244'),
(48, 'Prof.R.G.Ragel', 'Engineering', 'Darshana Jayasinghe, Aleksandar Ignjatovic, Roshan Ragel, Jude Angelo Ambrose, and Sri Parameswaran. 2021. QuadSeal: Quadruple Balancing to Mitigate Power Analysis Attacks with Variability Effects and Electromagnetic Fault Injection Attacks. ACM Trans. Des. Autom. Electron. Syst. 26, 5, Article 33 (September 2021), 36 pages. https://doi.org/10.1145/3443706'),
(49, 'Prof.R.G.Ragel', 'Engineering', 'Shafana, M.S., Ragel, R.G. and Kumara, T.N., 2021. An effective feature set for enhancing printed Tamil character recognition. Journal of the National Science Foundation of Sri Lanka, 49(2), pp.195–208. DOI: http://doi.org/10.4038/jnsfsr.v49i2.9466'),
(50, 'Prof.R.G.Ragel', 'Engineering', 'V. Gnanasambandapillai, J. Peddersen, R. Ragel and S. Parameswaran, \"FINDER: Find Efficient Parallel Instructions for ASIPs to Improve Performance of Large Applications,\" in IEEE Transactions on Computer-Aided Design of Integrated Circuits and Systems, vol. 39, no. 11, pp. 3577-3588, Nov. 2020, doi: 10.1109/TCAD.2020.3012211.'),
(51, 'Prof.R.G.Ragel', 'Engineering', 'Samarakoon, H., Punchihewa, S., Senanayake, A. et al. Genopo: a nanopore sequencing analysis toolkit for portable Android devices. Commun Biol 3, 538 (2020). https://doi.org/10.1038/s42003-020-01270-z'),
(52, 'Prof.R.G.Ragel', 'Engineering', 'Amin Malekpour, Roshan Ragel, Tuo Li, Haris Javaid, Aleksandar Ignjatovic, and Sri Parameswaran. 2020. Hardware Trojan Mitigation in Pipelined MPSoCs. ACM Trans. Des. Autom. Electron. Syst. 25, 1, Article 6 (January 2020), 27 pages. https://doi.org/10.1145/3365578'),
(53, 'Prof.R.G.Ragel', 'Engineering', 'Hinas A, Ragel R, Roberts J, Gonzalez F. A Framework for Multiple Ground Target Finding and Inspection Using a Multirotor UAS. Sensors. 2020; 20(1):272. https://doi.org/10.3390/s20010272'),
(54, 'Prof.R.S.Rajakaruna', 'Science', 'Thilakarathne, S.S., Wijewardena, N., Perera, P.K., Mallawa, C. and Rajakaruna, R.S. (2022) Filariasis in dogs brought to the Veterinary Teaching Hospital, University of Peradeniya, Sri Lanka. Veterinary Research. https://doi.org/10.1007/s00436-022-07742-x'),
(55, 'Prof.R.S.Rajakaruna', 'Science', 'Ranatunga, S., Dangolla, A., Sooriyapathirana, S.S.D. and Rajakaruna, R.S. (2022) High asymptomatic cases of babesiosis in dogs and comparison of diagnostic performance of conventional PCR vs blood smears. Acta Parasitologica. https://doi.org/10.1007/s11686-022-00549-x'),
(56, 'Prof.R.S.Rajakaruna', 'Science', 'Rajakaruna, M., Rajakaruna, H. and Rajakaruna, R. (2022) Dynamic regulations on mobility and vaccinations for controlling Covid-19 spread. Nature Scientific Reports 12:3554 | https://doi.org/10.1038/s41598-022-07371-5 '),
(57, 'Prof.R.S.Rajakaruna', 'Science', 'Kapukotuwa, R.W.M.G.K., Jayasena, N., Abeysekara, C.L., Weerakoon, K.C. and Rajakaruna R.S. (2022) High levels of microplastics in commercial salt and industrial salterns in Sri Lanka. Marine Pollution Bulletin 174. https://doi.org/10.1016/j.marpolbul. 2021.113239'),
(58, 'Prof.R.S.Rajakaruna', 'Science', 'De Silva, T.K., Rajakaruna, R.S., Rajapakse, R.P.V.J. and Perera, P.K. (2022) First molecular identification of Ancylostoma species in dogs in a rural tea estate community in Sri Lanka and the detection of other zoonotic gastrointestinal parasites. Acta Parasitologica. https://doi.org/10.1007/s11686-022-00531-7'),
(59, 'Prof.R.S.Rajakaruna', 'Science', 'Bandaranayaka, K.O., Dissanyakae, U.I., and Rajakaruna, R.S. (2022) Diversity and Geographic distribution of dog tick species in Sri Lanka and the life cycle of brown dog tick, Rhipicephalus sanguineus under laboratory conditions. Acta Parasitologica. doi: 10.1007/s11686-022-00622-5. '),
(60, 'Prof.R.S.Rajakaruna', 'Science', 'Diyes, G.C.P., Bandara, K.M.U.J., Rajakaruna, R.S. and Karunaratne, S.H.P.P. (2021) Acaricide resistance in the spinose ear tick, Otobius megnini (Acari: Argasidae) infesting racehorses in Sri Lanka. Journal of the National Science Foundation. 49 (4): 551 - 561 DOI: http://dx.doi.org/10.4038/jnsfsr.v49i4.10307'),
(61, 'Prof.R.S.Rajakaruna', 'Science', 'Bandaranayaka, K.O., Kularatne, S.A.M., Rajapakse, R.P.V.J., Abeysundara, U.B., Rajapaksha, R.M.M.A. and Rajakaruna, R.S. (2021) Human Otoacariasis in Two Climatically Diverse Districts in Sri Lanka: Seasonality, Risk Factors, and Case Notes. Acta Parasitologica. https://doi.org/10.1007/s11686-021-00372-w'),
(62, 'Prof.R.S.Rajakaruna', 'Science', 'Thilakarathne, S.S., Rajakaruna, R.S., Fernando, D., Rajapakse, R.P.V.J. and Perera, P.K. (2021) Comparison of gastro-intestinal parasites with zoonotic and anthroponotic potential in two subspecies of toque macaque (Macaca sinica) in Sri Lanka. Veterinary Parasitology: Regional Studies and Reports 24: 100558. https://doi.org/10.1016/j.vprsr.2021. 100558.'),
(63, 'Prof.R.S.Rajakaruna', 'Science', 'Diyes, G.C.P. and Rajakaruna, R.S. (2021) Teratological anomalies of an adult Asiatic blue tick, Rhipicephalus microplus (Acari: Ixodidae) Systematic and Applied Acarology. 26: 320–324.  https://doi.org/10.11158/saa.26.1.19'),
(64, 'Prof.R.S.Rajakaruna', 'Science', 'Mashkour, N., Ahasan, S.,  Barnes, A., Bell, I., Bowater, R.,  Elliman, J., Flint, M., Hamann, M., Jakob-Hoff, M., R.,  Jones,  K., Orduna, S.K., Loganathan, A.L., Rajakaruna, R., Mark Read, M., Walker, G., Work, T., Wittaker, M., Baverstock, W., Blyde, D., Crespo-Picazo, J.L., Eghbali, M., Freggi, D., Gardner, B., Giliam, J., Hale, H., Hyland, K.P., March, D., Mobaraki, A., Mohammadi, M., Nicolle, N., Owens, L., Parga, M., Robinson, D., Saladin, C., Spiby, K., Hipolito, T.V., Wrobel, D., Young, E. and Ariel, A. (2020) Disease Risk Analysis in sea turtles: A baseline study to inform conservation efforts. PLosOne. DOI: 10.1101/2020.03.10.985432'),
(65, 'Prof.R.S.Rajakaruna', 'Science', 'Dangolla, A., Wijesundara, D.L.R., Blair, D., Fernando, D.D., Wijesundera, K.K., Chathuranga, W.G.D. de Silva W.A.P.P. and Rajakaruna R.S. (2020) Canine trypanosomosis in Sri Lanka: An emerging problem reported from three distinct geographic locations. Parasitology International. https://doi.org/10.1016/j.parint. 2020.102129.'),
(66, 'Prof.K.B.S.N.Jinadasa', 'Engineering', 'Wijerathna, WSMSK; Lindamulla, LMLKB; Nanayakkara, KGN; Rathnayake, RMLD; Jegatheesan, V; Jinadasa, KBSN; Post-treatment of matured landfill leachate: Synthesis and evaluation of chitosan biomaterial based derivatives as adsorbents Environmental Research 1150182022 Academic Press https://doi.org/10.1016/j.envres.2022.115018'),
(67, 'Prof.K.B.S.N.Jinadasa', 'Engineering', 'Jegatheesan, V., Pachova, N., Velasco, P., Mowjood, M. I. M., Weragoda, S. K., Makehelwala, M., Trang, N. T. D., Dang, B.-T., Tran, C.-S., Vo, T.-K.-Q., Trang, N. T. T., Pham, H., Devanadera, M. C., Torrens, A., Bui, X.-T., Nguyen, P.-D., Lecciones, A., & Jinadasa, K. B. S. N. (2022). Co-development of an integrated assessment framework to evaluate the effectiveness and impact of selected nature-based water treatment technologies in Sri Lanka, The Philippines, and Vietnam. Environmental Quality Management, 1– 31. https://doi.org/10.1002/tqem.21922'),
(68, 'Prof.K.B.S.N.Jinadasa', 'Engineering', 'L.M.L.K.B. Lindamulla, N.K.R.N. Jayawardene, W.S.M.S.K. Wijerathne, M. Othman, K.G.N. Nanayakkara, K.B.S.N. Jinadasa, G.B.B. Herath, V. Jegatheesan, Treatment of mature landfill leachate in tropical climate using membrane bioreactors with different configurations, Chemosphere, Volume 307, Part 3, 2022, 136013, ISSN 0045-6535, https://doi.org/10.1016/j.chemosphere.2022.136013.'),
(69, 'Prof.K.B.S.N.Jinadasa', 'Engineering', 'Lindamulla, L., Nanayakkara, N., Othman, M. Shameen Jinadasa, Gemunu Herath & Veeriah Jegatheesan. Municipal Solid Waste Landfill Leachate Characteristics and Their Treatment Options in Tropical Countries. Curr Pollution Rep (2022). https://doi.org/10.1007/s40726-022-00222'),
(70, 'Prof.K.B.S.N.Jinadasa', 'Engineering', 'J. Ketharani, M.A.C.K. Hansima, Suresh Indika, D.R. Samarajeewa, Madhubhashini Makehelwala, K.B.S.N. Jinadasa, S.K. Weragoda, R.M.L.D. Rathnayake, K.G.N. Nanayakkara, Yuansong Wei, S.L. Schensul, Rohan Weerasooriya, A comparative study of community reverse osmosis and nanofiltration systems for total hardness removal in groundwater, Groundwater for Sustainable Development, Volume 18, 2022, 100800, ISSN 2352-801X, https://doi.org/10.1016/j.gsd.2022. 100800'),
(71, 'Prof.K.B.S.N.Jinadasa', 'Engineering', 'M.A.C.K. Hansima, A.T. Jayaweera, J. Ketharani, Tharindu Ritigala, Libing Zheng, D.R. Samarajeewa, K.G.N. Nanayakkara, Ajith C. Herath, Madhubhashini Makehelwala, K.B.S.N. Jinadasa, S.K. Weragoda, Yuansong Wei, Rohan Weerasooriya, Characterization of humic substances isolated from a tropical zone and their role in membrane fouling, Journal of Environmental Chemical Engineering, Volume 10, Issue 3, 2022, 107456, ISSN 2213-3437, https://doi.org/10.1016/j.jece.2022.107456.'),
(72, 'Prof.K.B.S.N.Jinadasa', 'Engineering', 'Goswami, P., Guruge, K.S., Tanoue, R., Tamamura, Y.A., Jinadasa, K.B.S.N., Nomiyama, K., Kunisue, T. and Tanabe, S., Occurrence of Pharmaceutically Active Compounds and Potential Ecological Risks in Wastewater from Hospitals and Receiving Waters in Sri Lanka. Environ Toxicol Chem, 41: 298-311, 2022. https://doi.org/10.1002/etc.5212'),
(73, 'Prof.K.B.S.N.Jinadasa', 'Engineering', 'Chaamila Pathirana, Abdul M. Ziyath, Prasanna Egodawatta, Nilanthi J.G.J. Bandara, K.B.S.N. Jinadasa, Erick R. Bandala, Buddhi Wijesiri, Ashantha Goonetilleke, Biosorption of heavy metals: Transferability between batch and column studies, Chemosphere, Volume 294, 2022, 133659, ISSN 0045-6535, https://doi.org/10.1016/j.chemosphere.2022.133659.'),
(74, 'Prof.K.B.S.N.Jinadasa', 'Engineering', 'Malalagama, T.P., Binghui, T., Jinadasa, K.B.S.N., Samaraweera, D.R., Yang, F., Removal of Fluoride in Water and Wastewater Using Electrodialysis/Electrodialysis Reverse Process: A Review. In: Dissanayake, R., Mendis, P., Weerasekera, K., De Silva, S., Fernando, S. (eds) ICSBE 2020. Lecture Notes in Civil Engineering, vol 174. Springer, Singapore. https://doi.org/10.1007/978-981-16-4412-2_43'),
(75, 'Prof.K.B.S.N.Jinadasa', 'Engineering', 'L.M.L.K.B. Lindamulla, V. Jegatheesan, K.B.S.N. Jinadasa, K.G.N. Nanayakkara, M.Z. Othman, Integrated mathematical model to simulate the performance of a membrane bioreactor, Chemosphere, Volume 284, 2021, https://doi.org/10.1016/j.chemosphere.2021.131319.'),
(76, 'Prof.K.B.S.N.Jinadasa', 'Engineering', 'Keerthi S. Guruge, Yukino A. Tamamura, Prasun Goswami, Rumi Tanoue, K.B.S.N. Jinadasa, Kei Nomiyama, Takeshi Ohura, Tatsuya Kunisue, Shinsuke Tanabe, Masato Akiba, The association between antimicrobials and the antimicrobial-resistant phenotypes and resistance genes of Escherichia coli isolated from hospital wastewaters and adjacent surface waters in Sri Lanka, Chemosphere, Volume 279, 2021, 130591, ISSN 0045-6535, https://doi.org/10.1016/j.chemosphere.2021.130591.'),
(77, 'Prof.K.B.S.N.Jinadasa', 'Engineering', 'Thamali Perera, James McGree, Prasanna Egodawatta, K.B.S.N. Jinadasa, Ashantha Goonetilleke, A Bayesian approach to model the trends and variability in urban stormwater quality associated with catchment and hydrologic parameters, Water Research, Volume 197, 2021, 117076, ISSN 0043-1354, https://doi.org/10.1016/j.watres.2021.117076.'),
(78, 'Prof.K.B.S.N.Jinadasa', 'Engineering', 'Thamali Perera, James McGree, Prasanna Egodawatta, K.B.S.N. Jinadasa, Ashantha Goonetilleke, New conceptualization of first flush phenomena in urban catchments, Journal of Environmental Management, Volume 281, 2021, 111820, ISSN 0301-4797, https://doi.org/10.1016/j.jenvman.2020.111820'),
(79, 'Prof.K.B.S.N.Jinadasa', 'Engineering', 'Thamali Perera, James McGree, Prasanna Egodawatta, K.B.S.N. Jinadasa, Ashantha Goonetilleke, Catchment based estimation of pollutant event mean concentration (EMC) and implications for first flush assessment, Journal of Environmental Management, Volume 279, 2021, 111737, ISSN 0301-4797, https://doi.org/10.1016/j.jenvman.2020.111737.'),
(80, 'Prof.K.B.S.N.Jinadasa', 'Engineering', 'Tharindu Ritigala, Yanlin Chen, Jiaxi Zheng, Hailu Demissie, Libing Zheng, Dawei Yu, Qianwen Sui, Meixue Chen, Jinxing Zhu, Hua Fan, Jiao Li, Qian Gao, Sujithra.K. Weragoda, Rohan Weerasooriya, K.B.S.N. Jinadasa, Yuansong Wei, Comparison of an integrated short-cut biological nitrogen removal process with magnetic coagulation treating swine wastewater and food waste digestate, Bioresource Technology, Volume 329, 2021, 124904, ISSN 0960-8524, https://doi.org/10.1016/j.biortech.2021.124904.'),
(81, 'Prof.K.B.S.N.Jinadasa', 'Engineering', 'M.A.C.K. Hansima, Madhubhashini Makehelwala, K.B.S.N. Jinadasa, Yuansong Wei, K.G.N. Nanayakkara, Ajith C. Herath, Rohan Weerasooriya, Fouling of ion exchange membranes used in the electro dialysis reversal advanced water treatment: A review, Chemosphere, Volume 263, 2021, 127951, ISSN 0045-6535, https://doi.org/10.1016/j.chemosphere.2020.127951.'),
(82, 'Prof.K.B.S.N.Jinadasa', 'Engineering', 'Indika, S.; Wei, Y.; Hu, D.; Ketharani, J.; Ritigala, T.; Cooray, T.; Hansima, M.A.C.K.; Makehelwala, M.; Jinadasa, K.B.S.N.; Weragoda, S.K.; Weerasooriya, R. Evaluation of Performance of Existing RO Drinking Water Stations in the North Central Province, Sri Lanka. Membranes 2021, 11, 383. https://doi.org/10.3390/membranes11060383'),
(83, 'Prof.K.B.S.N.Jinadasa', 'Engineering', 'Titus Cooray, Junya Zhang, Hui Zhong, Libing Zheng, Yuansong Wei, Sujithra K. Weragoda, K.B.S.N. Jinadasa, Rohan Weerasooriya, Profiles of antibiotic resistant and microbial community in groundwater of CKDu prevalence zones in Sri Lanka, Journal of Hazardous Materials, Volume 403, 2021, 123816, ISSN 0304-3894, https://doi.org/10.1016/j.jhazmat.2020.123816.'),
(84, 'Prof.D.N.B.Gunawardane', 'Arts', 'Gunewardena, Dileni & Seck, Abdoulaye. 2020. \"Heterogeneity in entrepreneurship in developing countries: Risk, credit, and migration and the entrepreneurial propensity of youth and women,\" Review of Development Economics, Wiley Blackwell, vol. 24(3), pages 713-725, August. https://doi.org/10.1111/rode.12703'),
(85, 'Prof.D.N.B.Gunawardane', 'Arts', 'King, Elizabeth M. & Gunewardena, Dileni. 2022. Human Capital and Gender Inequality in Middle Income Countries: Schooling, Learning and Socioemotional Skills in the Labour Market. Routledge, London. https://doi.org/10.4324/9781003171652'),
(86, 'Prof.D.N.B.Gunawardane', 'Arts', 'Gunewardena, Dileni & Siyambalapitiya, Sumini. 2023. “Electricity Usage as a Proxy Indicator for Poverty Targeting”. Sri Lanka Journal of Economic Research. 10(2), pp.115–125. http://doi.org/10.4038/sljer.v10i2.186'),
(NULL, 'Prof.P.Samarasekara', 'Science', 'R.M.T.D.Rajapaksha, P. Samarasekara, P. G. D. C. K. Karunarathna, and C. A. N. Fernando “Improvement of gas sensitivity of ferric oxide thin films by adding Mn nanoparticles” Bulletin of materials science 44, Article number 182 (2021)  \r\n  DOI: https://doi.org/10.1007/s12034-021-02473-8\r\n'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Abeywickrama HM, Wimalasiri S, Koyama Y, Uchiyama M, Shimizu U, Chandrajith R, Kakihara N, Nanayakkara N (2020) Quality of life and symptom burden among chronic kidney disease of uncertain etiology (CKDu) patients in Girandurukotte, Sri Lanka. International Journal of Environmental Research and Public Health 17: 4041. http://doi.org/10.3390/ijerph17114041.'),
(NULL, 'Prof.T.M.W.J.Bandara', 'Science', 'T.M.W.J. Bandara, M. Furlani, I. Albinsson, A. Wulff, B.E. Mellander, Diatom frustules enhancing efficiency in gel polymer electrolyte based dye-sensitized solar cells with multilayer photoelectrodes, Nanoscale Advances, 2 (2020) 199-209. \r\nhttps://doi.org/10.1039/C9NA00679F \r\n'),
(NULL, 'Prof.T.M.W.J.Bandara', 'Science', 'G.B.M.M.M. Nishshanke, A.K. Arof, T.M.W.J. Bandara, Review on mixed cation effect in gel polymer electrolytes for quasi solid-state dye-sensitized solar cells, Ionics, 26 (2020) 3685–3704. https://doi.org/10.1007/s11581-020-03668-5'),
(NULL, 'Prof.T.M.W.J.Bandara', 'Science', 'T.M.W.J. Bandara, S.L.N. Senavirathna, H.M.N. Wickramasinghe, K. Vignarooban, L.A. De Silva, M.A.K.L. Dissanayake, I. Albinsson, B.-E. Mellander, Binary counter ion eﬀects and dielectric behavior of iodide ion conducting gel-polymer electrolytes for high-eﬃciency quasi-solid-state solar cells, Phys. Chem. Chem. Phys., 22 (2020) 12532 -12543. https://doi.org/10.1039/D0CP01547D '),
(NULL, 'Prof.T.M.W.J.Bandara', 'Science', 'T.M.W.J. Bandara, L. Ajith DeSilva, L.B.E. Gunasekara, Sunil Dehipawala, B.-E. Mellander, Determination of charge carrier transport parameters in a polymer electrolyte intended for Li-ion batteries using electrochemical impedance analysis, J. Solid. State. Electrochem., 24 (2020) 1207–1216. https://doi.org/10.1007/s10008-020-04604-3'),
(NULL, 'Prof.T.M.W.J.Bandara', 'Science', 'Zachary Welchel, L. Ajith DeSilva, T.M.W.J. Bandara, Properties of tris (8-hydroxyquinoline) aluminum thin films fabricated by spin coating from static and dynamic dispense methods, Optical Materials, 108 (2020) 110447. https://doi.org/10.1016/j.optmat.2020.110447 '),
(NULL, 'Prof.T.M.W.J.Bandara', 'Science', 'G.B.M.M.M., Nishshanke, B.D.K.K. Thilakarathna, I. Albinsson, B-E. Mellander, and T.M.W.J. Bandara. Multi-layers of TiO2 nanoparticles in the photoelectrode and binary iodides in the gel polymer electrolyte based on poly (ethylene oxide) to improve quasi solid-state dye-sensitized solar cells, Journal of Solid State Electrochemistry, 25 (2), (2021) 707-720. https://doi.org/10.1007/s10008-020-04846-1 '),
(NULL, 'Prof.T.M.W.J.Bandara', 'Science', 'T.M.W.J Bandara, H.M.N. Wickramasinghe, K. Wijayaratne, L. Ajith DeSilva, and A.A.I. Perera. Quasi-solid-state dye-sensitized solar cells utilizing TiO2/graphite composite counter electrode and TiO2/N719 sensitizer photoelectrode for low-cost power generation, Journal of Materials Science: Materials in Electronics, 32(22), (2021) 26758-26769. https://doi.org/10.1007/s10854-021-07053-4'),
(NULL, 'Prof.T.M.W.J.Bandara', 'Science', 'T.M.W.J. Bandara, L.B.E. Gunasekara, S.M.S. Gunathilake, B.-E. Mellander, Transport parameters of charge carriers in PEO-LiTf-based, plasticized, composite, and plasticized-composite electrolytes intended for Li-ion batteries, Ionics, 28, (2022) 2701–2714. https://doi.org/10.1007/s11581-022-04540-4'),
(NULL, 'Prof.T.M.W.J.Bandara', 'Science', 'T.M.W.J., Bandara, J.M.C. Hansadi F. Bella, A review of textile dye-sensitized solar cells for wearable electronics, Ionics, 28 (2022) 2563–2583. https://doi.org/10.1007/s11581-022-04582-8'),
(NULL, 'Prof.T.M.W.J.Bandara', 'Science', 'T.M.W.J. Bandara, T.M.A.A.B. Thennakoon, G.G.D.M.G. Gamachchi, L.R.A.K. Bandara, B.M.K. Pemasiri, U. Dahanayake, An electrochemical route to exfoliate vein graphite into graphene with black tea, Materials Chemistry and Physics, 289 (2022) 126450. https://doi.org/10.1016/j.matchemphys.2022.126450 '),
(NULL, 'Prof.T.M.W.J.Bandara', 'Science', 'L.K. Narangammana, Y.M.D.C.Y., Bandara, L.A. DeSilva, T.M.W.J. Bandara, Organic-Inorganic Hybrid Thermocouple Intended for Thermoelectric Generators Using Low-Cost Nontoxic Materials, Journal of Electronic Materials, 51, (2022) 5462–5472 https://doi.org/10.1007/s11664-022-09799-x '),
(NULL, 'Prof.T.M.W.J.Bandara', 'Science', 'C. Jayathilake, G.P. Dilangani, S. Bandara, Z. Nazeer, N. Thilini, TMWJ Bandara, & E.Y. Fernando, The use of Statin-class compounds to suppress methanogenesis in lake sediment inoculated microbial fuel cells. Bioresource Technology Reports, 20 (2022) 101272. https://doi.org/10.1016/j.biteb.2022.101272 '),
(NULL, 'Prof.T.M.W.J.Bandara', 'Science', 'A.D.T. Medagedara, N.M. Waduge, T.M.W.J. Bandara, I.G.K.J. Wimalasena, M. Dissanayake, K. Tennakone, R.M.G. Rajapakse, C.P. Rupasinghe, G.R.A. Kumara, Triethylammonium thiocyanate ionic liquid electrolyte-based supercapacitor fabricated using coconut shell-derived electronically conducting activated charcoal electrode material, Journal of Energy Storage 55 (B) (2022) 105628. https://doi.org/10.1016/j.est.2022.105628'),
(NULL, 'Prof.A.D.L.C.Perera', 'Science', '“Fast and high adsorption of cadmium ions from aqueous solutions by acid-activated and pyrolyzed coconut coir”, Bhanuka P.K. Ekanayake , H.E. Darshi Tharika , A.D.L. Chandani Perera and Nilwala Kottegoda, Desalination and Water Treatment, 236 (2021) 99–107, \r\ndoi: 10.5004/dwt.2021.27680 \r\n'),
(NULL, 'Prof.A.D.L.C.Perera', 'Science', '“A Novel Green Approach to Synthesize Curcuminoid-Layered Double Hydroxide Nanohybrids: Adroit Biomaterials for Future Antimicrobial Applications”, Chamalki Madhusha, Kumudu Rajapaksha, Imalka Munaweera, Madhavi de Silva, Chandani Perera, Gayan Wijesinghe, Manjula Weerasekera, Dinesh Attygalle, Chanaka Sandaruwan, and Nilwala Kottegoda, ACS Omega, 6, 14 (2021) 9600-9608'),
(NULL, 'Prof.A.D.L.C.Perera', 'Science', '“Phosphate functionalized activated carbon sachet filters for drinking water purification”,\r\nChamalki Madhusha,   Kavindya Weerasinghe,   Imalka Munaweera,   Chandani Perera,   Gayan Wijesinghe,   Manjula M. Weerasekera,   Yugantha Idangodage,   Chandrakantha Senajith Kalpage  and  Nilwala Kottegoda,  Environmental Science: Water Research & Technology, (2022), DOI: 10.1039/D2EW00623E\r\n'),
(NULL, 'Prof.A.D.L.C.Perera', 'Science', '“Sustainable Synthesis of Highly Functionalized Activated Carbon using Plasma Technology”, Sehan Jayasinghe, Dumindu Pasan Siriwardena, Imalka Munaweera, Chandani Perera, Nilwala Kottegoda, ChemPlusChem, 87 (10) (2022)\r\n https://doi.org/10.1002/cplu.202200202\r\n'),
(NULL, 'Prof.A.D.L.C.Perera', 'Science', '“Synthesis and structural characterization of copper nanoparticles doped activated carbon derived from coconut coir for drinking water purification”, C. Madhusha, T. Jayasundara, I. Munaweera, C. Perera, G. Wijesinghe, M. Weerasekera, C. Sandaruwan, A. Meiyazhagan, F.C. Robles Hernandez, P.M. Ajayan, N. Kottegoda, Materials Today Chemistry 27 (2023) 101312\r\nhttps://doi.org/10.1016/j.mtchem.2022.101312 \r\n'),
(NULL, 'Prof.M.A.S.P.K.Malaviarachchi', 'Science', 'Name of Book: Gold and Platinum Group Elements in Metamorphic Rocks of east Gondwana\r\nISBN: 978-620-3-02714-3\r\nPublisher: Lambert Academic Publishing, Germany (2020)\r\n'),
(NULL, 'Prof.M.A.S.P.K.Malaviarachchi', 'Science', 'Patrick Asamoah Sakyi, Ben-Xun Su, Johnson Manu, Daniel Kwayisi, Chris Y Anani, Melesse Alemayehu, Sanjeewa PK Malaviarachchi, Prosper M Nude, Ben-Can Su. Origin and tectonic significance of the metavolcanic rocks and mafic enclaves from the Palaeoproterozoic Birimian Terrane, SE West African Craton, Ghana., Geological Magazine, 157, 1349-1366 (2020). IF:2.65, TC:01'),
(NULL, 'Prof.M.A.S.P.K.Malaviarachchi', 'Science', 'PL Dharmapriya, Sanjeewa PK Malaviarachchi, Leo M Kriegsman, Andrea Galli, Brendan Dyck, K Sajeev, Ben-Xun Su, Amarasooriya Pitawala. Symplectite growth in the presence of alkaline fluids: evidence from high-aluminous metasediments of the Highland Complex, Sri Lanka. Mineralogy and Petrology, 114, 515–538(2020). IF:1.68, TC:00'),
(NULL, 'Prof.M.A.S.P.K.Malaviarachchi', 'Science', 'Prasanna L Dharmapriya, Sanjeewa PK Malaviarachchi, Andrea Galli, Leo M Kriegsman, Yasuhito Osanai, K Sajeev, Ben‐Xun Su, Toshiaki Tsunogae, Chengli Zhang, Tatsuro Adachi, Chandrasekara B Dissanayake, Nalaka Deepal Subasinghe. Hybrid phase equilibria modelling with conventional and trace element thermobarometry to assess the P–T evolution of UHT granulites: An example from the Highland Complex, Sri Lanka. Journal of Metamorphic Geology, https://doi.org/10.1111/jmg.12569. (2020), IF:4.57, TC:00'),
(NULL, 'Prof.M.A.S.P.K.Malaviarachchi', 'Science', 'Sanjeewa PK Malaviarachchi, P. L Dharmapriya, Some trace element ratios hardly modify during metamorphism of pelitic granulites as evidencd from the Highland Complex, Sri Lanka, Lithos, https://doi.org/10.1016/j.lithos.2021.106120 (2021) , IF:3.91, TC:02'),
(NULL, 'Prof.M.A.S.P.K.Malaviarachchi', 'Science', 'Sanjeewa P.K. Malaviarachchi, M. Satish-Kumar, Toshiro Takahashi. New Sr-Nd isotope data record juvenile and ancient crust-mantle melt interactions in the Vijayan Complex, Sri Lanka, Journal of Geology, 129, 233-253 (2021) , IF:2.05, TC:08'),
(NULL, 'Prof.M.A.S.P.K.Malaviarachchi', 'Science', 'M. Satish-Kumar, Momoko Shirakawa, Akari Imura,  Naho Otsuji-Makino, Rikako Imanaka-Nohara, Sanjeewa P.K. Malaviarachchi, Ian C. W. Fitzsimons, Krishnan Sajeew, Geoffrey Grantham, Brian Windley, Tomokazu Hokada, Toshiro Takahashi, Gen Shimoda, Kosuke T. Goto. A geochemical and isotopic perspective on tectonic setting and depositional environment of Precambrian metacarbonate rocks in collisional orogenic belt. GR Focus Invited Review, Gondwana Research, 96, 163-204 (2021) , IF:8.12, TC:09'),
(NULL, 'Prof.M.A.S.P.K.Malaviarachchi', 'Science', 'N Samarakoon, SPK Malaviarachchi, A Senaratne, A Wijayasinghe. Gold occurrences in copper-magnetite-apatite deposit at Seruwila, Sri Lanka. Ore and Energy Resource Geology 8, 100014 (2021) , IF:3.71, TC:00.'),
(NULL, 'Prof.M.A.S.P.K.Malaviarachchi', 'Science', 'Jing Wang, Ben-Xun Su, Chen Chen, Silvio Ferrero, Sanjeewa PK Malaviarachchi, Patrick Asamoah Sakyi, Yue-Heng Yang, PL Dharmapriya. Crustal Derivation of the ca. 475 Ma Eppawala Carbonatites in Sri Lanka. Journal of Petrology 62 (11) (2021) , IF:4.57, TC:03'),
(NULL, 'Prof.M.A.S.P.K.Malaviarachchi', 'Science', 'Harinadha Reddy, M Satish-Kumar, Niels Jöns, Sanjeewa PK Malaviarachchi, Vinod O Samuel, PM George. The timing, duration and conditions of UHT metamorphism in remnants of the former eastern Gondwana. Journal of Petrology 62 (12) (2021) , IF:4.57, TC:03'),
(NULL, 'Prof.M.A.S.P.K.Malaviarachchi', 'Science', 'PL Dharmapriya, LM Kriegsman, SPK Malaviarachchi. Spatial distribution of ultrahigh-temperature granulites of the Highland Complex of Sri Lanka: Lowermost continental crust above an ultrahot palaeo-Moho. Lithos 404, 106484 (2021) , IF:3.91, TC:04'),
(NULL, 'Prof.M.A.S.P.K.Malaviarachchi', 'Science', 'Ben‐Xun Su, Jing Wang, Meng‐Meng Cui, Yong Wu, Kwan‐Nang Pang, Sanjeewa PK Malaviarachchi, PL Dharmapriya. Element Partitioning and Li‐O Isotope Fractionation Between Silicate Minerals and Crustal‐Derived Carbonatites and Their Implications. Journal Geophysical Research, 6. (2022) IF:4.26, TC:00.'),
(NULL, 'Dr.K.W.L.K.Weerasinghe', 'Agriculture', 'Falster, D., Gallagher, R., Wenk, E. H., Wright, I. J., Indiarto, D., Andrew, S. C., O’Sullivan, O. S., ..Weerasinghe, L.K., & Ziemińska, K. (2021). AusTraits, a curated plant trait database for the Australian flora. Scientific Data, 8(1), 1-20.'),
(NULL, 'Dr.K.W.L.K.Weerasinghe', 'Agriculture', 'Zhu, L., Bloomfield, K.J., Asao, S., Tjoelker, M.G., Egerton, J.J., Hayes, L., Weerasinghe, L.K., Creek, D., Griffin, K.L., Hurry, V. and Liddell, M., & Atkin, O. K. (2021). Acclimation of leaf respiration temperature responses across thermally contrasting biomes. New Phytologist, 229(3), 1312-1325.'),
(NULL, 'Dr.K.W.L.K.Weerasinghe', 'Agriculture', 'Ellsworth, D. S., Crous, K. Y., De Kauwe, M. G., Verryckt, L. T., Goll, D., Zaehle, S., Weerasinghe, K.W.L.K. . & Wright, I. J. (2022). Convergence in phosphorus constraints to photosynthesis in forests around the world. Nature communications, 13(1), 5005.'),
(NULL, 'Prof.W.M.Thilakarathne', 'Dental Sciences', 'Sigera LSM, Gunawardane SR, Malkanthi MA, Jayasinghe RD, Sitheeque MAM, Tilakaratne WM, Jayasekera PI. Histoplasma capsulatum Caused a Localized Tongue Ulcer in a Non-HIV Patient-A Case From Nonendemic Country. Ear Nose Throat J. 2020 July;99(6):379-81 doi: 10.1177/0145561319844246.'),
(NULL, 'Prof.W.M.Thilakarathne', 'Dental Sciences', 'PVKS Hettiarachchi, Primali Jayasooriya, Hemantha Amarasinghe, BSMS Siriwardena, Deepashika Wijerathne, Samantha Kumara Kithalawaarachchi, WM Tilakaratne, Ruwan D Jayasinghe. Knowledge and Attitudes of Nursing Students Towards Smokeless Tobacco and Areca Nut Control in Central Province of Sri Lanka. Asian Pac J Cancer Care, 2020, 5(3):133-138. '),
(NULL, 'Prof.W.M.Thilakarathne', 'Dental Sciences', 'BSMS Siriwardena, MNG Pushpakumara Udagama, TMPB Tennakoon, DADW Athukorala, PR Jayasooriya, WM Tilakaratne. Clinical and demographic characteristics of adenomatoid odontogenic tumors: analysis of 116 new cases from a single center. Brazilian J of Otorhinolaryngology, 2020; Jul 21:S1808-8694(20)30103-8. doi: 10.1016/j.bjorl.2020.06.00'),
(NULL, 'Prof.W.M.Thilakarathne', 'Dental Sciences', 'RA Welikala, P Remagnino, JH Lim, CS Chan, S Rajendran, TG Kallarakkal, RB Zain, RD Jayasinghe, J Rimal, A Ross Kerr, R Amtha, K Patil1, WM Tilakaratne, J Gibson, SC Cheong and SA Barman. Automated Detection and Classification of Oral Lesions using Deep Learning for Early Detection of Oral Cancer. IEEE Access;2020;8:132677-132693. '),
(NULL, 'Prof.W.M.Thilakarathne', 'Dental Sciences', 'BSMS Siriwardena, HDNU Karunathilake, PVR Kumarasiri, WM Tilakaratne. Impact of Histological and Molecular Parameters on Prognosis of Oral squamous cell carcinoma. BioMed Research International, 2020, doi.org/10.1155/2020/2059240.'),
(NULL, 'Prof.W.M.Thilakarathne', 'Dental Sciences', 'RA Welikala, P Remagnino, JH Lim, CS Chan, S Rajendran, TG Kallarakkal, RB Zain, RD Jayasinghe, J Rimal, A Ross Kerr, R Amtha, K Patil1, WM Tilakaratne, J Gibson, SC Cheong and SA Barman. Fine-Tuning Deep Learning Architectures for Early Detection of Oral Cancer. Lecture Notes in Computer Science, 2020; vol 12508. Springer, Cham. https://doi.org/10.1007/978-3-030-64511-3_3'),
(NULL, 'Prof.W.M.Thilakarathne', 'Dental Sciences', 'Daniel Lim, Chuey Chuan Tan, WM Tilakaratne,Yet Ching Goh. Sclerosing odontogenic carcinoma -review of all published cases: is it a justifiable addition as a malignancy? Braz J Otorhinolaryngoy. 2021 Feb; doi: 10.1016/j.bjorl.2021.01.007. '),
(NULL, 'Prof.W.M.Thilakarathne', 'Dental Sciences', 'RD Jayasinghe, PR Jayasooriya, H Amarasinghe, PVKS Hettiarachchi, BSMS Siriwardena, UKYGDM Wijeratne, SK Kithalawarachchi, WM Tilakaratne. Evaluation of successfulness of capacity buiding programmes on smkokeless tobacco and arecanut cessation. Asian Pac J Cancer Prev, 2021;22(4), 1287-1293.'),
(NULL, 'Prof.W.M.Thilakarathne', 'Dental Sciences', 'NH Senarath, PR Jayasooriya, BSMS Siriwardena, WM Tilakaratne. Epithelial dysplasia at excision margins of oral squamous cell carcinoma; a review on relationship to clinicopathological parameters and prognosis. Asian Pac J Cancer Prev; 2021 Aug 1;22(8):2313-2321. doi: 10.31557/APJCP.2021.22.8.2313.'),
(NULL, 'Prof.W.M.Thilakarathne', 'Dental Sciences', 'Athukorala IA, Tilakaratne WM, Jayasinghe RD. Areca Nut Chewing: Initiation, Addiction, and Harmful Effects Emphasizing the Barriers and Importance of Cessation. J Addict. 2021 Jun 3;2021:9967097. doi: 10.1155/2021/9967097. '),
(NULL, 'Prof.W.M.Thilakarathne', 'Dental Sciences', 'Mohomed Mahees, Hemantha Kumara Amarasinghe, Udaya Usgodaarachchi, Nilantha Rathnayake,W M Tilakarathne, Suresh Shanmuganathen, Sajeeva Ranaweera, Palitha Abeykoon. A Sociological Analysis and Exploration of Factors Associated with Commercial Preparations of Smokeless Tobacco Use in Sri Lanka. Asian Pac J Cancer Prev, 2021;22 (6), 1753-1759.'),
(NULL, 'Prof.W.M.Thilakarathne', 'Dental Sciences', 'R Hannah, Ramani P, Tilakaratne WM, Sukumaran G, Ramasubramanian A, Krishnan RP. Critical appraisal of different triggering pathways for the pathobiology of pemphigus vulgaris-A review. Oral Dis. 2021 Jun 21. doi: 10.1111/odi.13937. '),
(NULL, 'Prof.W.M.Thilakarathne', 'Dental Sciences', 'PR Jayasooriya, WAMUL Abeyasinghe, RLPR Liyange, GN Uthpali, WM Tilakaratne. Diagnostic Enigma of Adenoid Ameloblastoma: Literature Review Based Evidence to Consider It as a New Sub Type of Ameloblastoma. Head Neck Pathol;2022; 50 (9) ; 927-936 doi: 10.1007/s12105-021-01358-w. '),
(NULL, 'Prof.W.M.Thilakarathne', 'Dental Sciences', 'Goh yet Ching, BSMS Siriwardena, WM Tilakaratne. Association of clinicopathological factors and treatment modalities in the recurrence of ameloblastoma: Analysis of 624 cases. J Oral Pathol Med 2021 Oct;50(9):927-936. doi: 10.1111/jop.13228.'),
(NULL, 'Prof.W.M.Thilakarathne', 'Dental Sciences', 'Padmanabha Kumar Govindaraj, Thomas George Kallarakkal, Rosnah Mohd Zain Wanninayake Mudiyanselage Tilakaratne, Huai Lin Lew. Expression of Ki-67, Cornulin and ISG15 in non-involved mucosal surgical margins as predictive markers for relapse in oral squamous cell carcinoma (OSCC).  PLoS One; 2021 Dec 23;16(12):e0261575. doi: 10.1371/journal.pone.0261575.'),
(NULL, 'Prof.W.M.Thilakarathne', 'Dental Sciences', 'Jue Young Kim, Jin Kim, B. M. Ratnayake Bandara, Wanninayake M. Tilakaratne and Dokyeong Kim.   Leaf extract of Osbeckia octandra induces apoptosis in oral squamous cell carcinoma cells. BMC complimentary Medicine and Therapies; 2022 doi.org/10.1186/s12906-022-03505-4.'),
(NULL, 'Prof.W.M.Thilakarathne', 'Dental Sciences', 'Gubod E, Ramanathan A, Chong Mei Yee S, WM Tilakaratne. Bone Formation in Pleomorphic Adenoma: A Case Report. Cureus 2022;14(3): e22868. doi:10.7759/cureus.22868.'),
(NULL, 'Prof.W.M.Thilakarathne', 'Dental Sciences', 'TG Kallarakkal, BSMS Siriwardena, A Samaranayake, RK De Silva, WM Tilakaratne. A Validated Predictive Model for Risk of Nodal Metastasis in Node Negative Oral Squamous Cell Carcinoma of the Buccal mucosa and tongue. J Oral Pathol Med 2022; 51(5):436-443. doi: 10.1111/jop.13294.');
INSERT INTO `pubnew` (`id`, `name`, `faculty`, `publication`) VALUES
(NULL, 'Prof.W.M.Thilakarathne', 'Dental Sciences', 'Rajendran S, Lim JH, Yogalingam K, Kallarakkal TG, Zain RB, Jayasinghe RD, Rimal J, Kerr AR, Amtha R, Patil K, Welikala RA, Lim YZ, Remagnino P, Gibson J, Tilakaratne WM, Liew CS, Yang YH, Barman SA, Chan CS, Cheong SC. Image collection and annotation platforms to establish a multi-source database of oral lesions. Oral Dis. 2022 Apr 10. doi: 10.1111/odi.14206. '),
(NULL, 'Prof.W.M.Thilakarathne', 'Dental Sciences', 'Muller S, Tilakaratne WM. Update from the 5th Edition of the World Health Organization Classification of Head and Neck Tumors: Tumours of the Oral Cavity and Mobile Tongue. Head Neck Pathol. 2022 Mar;16(1):54-62. doi: 10.1007/s12105-021-01402-9.'),
(NULL, 'Prof.W.M.Thilakarathne', 'Dental Sciences', 'Hettiarachchi Pilana Vithanage Kalani Shihanika, Piyarathne Nadisha, Siriwardena Bogahawatte Samarakoon Mudiyanselage Samadarani, Jayasinghe Ruwan Duminda , Perera Sriyani, Tilakaratne Wanninayake Mudiyanselage. Controversies in verruco papillary lesions of the oral cavity-A systematic review. Oral Dis 2022 Jul 8. doi: 10.1111/odi.14306. Online ahead of print.'),
(NULL, 'Prof.W.M.Thilakarathne', 'Dental Sciences', 'Bouvard V, Nethan ST, Singh D, Warnakulasuriya S, Mehrotra R, Chaturvedi AK, Chen TH, Ayo-Yusuf OA, Gupta PC, Kerr AR, Tilakaratne WM ---- Lauby-Secretan B. IARC Perspective on Oral Cancer Prevention. N Engl J Med. 2022 Nov 24;387(21):1999-2005. doi: 10.1056/NEJMsr2210097. '),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Abeywickrama HM, Wimalasiri S, Koyama Y, Uchiyama M, Shimizu U, Chandrajith R, Nanayakkara N (2020) Assessment of nutritional status and dietary pattern of a rural adult population in dry zone, Sri Lanka. International Journal of Environmental Research and Public Health 17(1); 150; https://doi.org/10.3390/ijerph17010150.'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Diyabalanage S, Dangolla A, Mallawa C, Rajapakse S, Chandrajith R (2020) Bioavailability of selenium (Se) in cattle population in Sri Lanka based on qualitative determination of glutathione peroxidase (GSH-Px) activities. Environmental Geochemistry and Health 42: 617–624. https://doi.org/10.1007/s10653-019-00395-3'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Chandrajith R, Diyabalanage S, Dissanayake CB (2020) Geogenic fluoride and arsenic in ground- water of Sri Lanka and its implications to community health. Groundwater for Sustainable Development 10: 100359. https://doi.org/10.1016/j.gsd.2020.100359.'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Fernando WBNT, Nanayakkara N, Gunarathne L, Chandrajith R (2020) Serum and urine fluoride levels in populations of high environmental fluoride exposure with endemic CKDu: a case–control study from Sri Lanka. Environmental geochemistry and health 42(5): 1497-1504. https://doi.org/10.1007/s10653-019-00444-x.'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Gayantha K, Routh J, Anupama K, Lazar J, Prasad S, Chandrajith R, Roberts P, Gleixner G (2020) Reconstruction of the Late Holocene climate and environmental history from North Bolgoda Lake, Sri Lanka using lipid biomarkers and pollen records. Journal of Quaternary Science 35: 514-525. https://doi.org/10.1002/jqs.3196.'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Jayathunga K, Diyabalanage S, Frank AH, Chandrajith R, Barth JAC (2020) Influences of seawater intrusion and anthropogenic activities on a coastal aquifer system in Sri Lanka: evidence from hydrogeochemical and stable isotope data. Environmental Science and Pollution Research 27: 23002–23014. https://doi.org/10.1007/s11356-020-08759-4.'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Rajakaruna TPB, Udawatte C, Chandrajith R, Rajapakse RMG (2020) Non-hazardous Process for Extracting Pure Titanium Dioxide Nano-rods from Geogenic Ilmenite. ACS Omega 5; 16176-16182. https://doi.org/10.1021/acsomega.0c01756.'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Gunawardena SA, Gunawardana JW, Chandrajith R, Thoradeniya T, Jayasinghe S (2020) Renal bioaccumulation of trace elements in urban and rural Sri Lankan populations: a preliminary study based on post mortem tissue analysis. Journal of Trace Elements in Medicine and Biology 61: 126563. https://doi.org/10.1016/j.jtemb.2020.126565.'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Nanayakkara S, Senevirathna STMLD, Harada KH, Chandrajith R, Nanayakkara N, Koizumu A (2020) Influence of fluoride on chronic kidney disease of uncertain aetiology (CKDu) in Sri Lanka. Chemosphere 257: 127186. https://doi.org/10.1016/j.chemosphere.2020.127186.'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Udeshani WAC, Dissanayake HMKP, Chandrajith R, Gunatilake S (2020) Assessment of groundwater quality using water quality index (WQI): a case study of a hard rock terrain in Sri Lanka. Groundwater for Sustainable development 11: 100421. https://doi.org/10.1016/j.gsd.2020.100421.'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Balasooriya S, Munasinghe H, Herath AT, Diyabalanage S, Ileperuma OA, Manthrithilake H, Daniel C, Amann K, Zwiener C, Barth JAC, Chandrajith R (2021) Possible links between groundwater geochemistry and chronic kidney disease of unknown etiology (CKDu): an investigation from the Ginnoruwa region in Sri Lanka. Exposure and Health 12: 823-834. https://doi.org/10.1007/s12403-019-00340-w.\r\n\r\n'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Senarathne S, Jayawardana JMCK, Edirisinghe EANV, Chandrajith R (2021) Geochemical and isotope evidence for groundwater mineralization in a semi-arid river basin, Sri Lanka. Applied Geochemistry 124:104799. https://doi.org/10.1016/j.apgeochem.2020.104799.'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Senanayke I, Piyasiri S, Chandrajith R, Nandalal W, Ranatunga K (2021) Assessment of Groundwater Quality Using Multivariate Statistical Analysis in the Medawachchiya Area and the Huruluwewwa Areas in Anuradhapura District. KDU Journal of Multidisciplinary Studies (KJMS) 3(1): 80-93.  '),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Gayantha K, Roberts P, Routh J, Wedage O, Ott F, Frenzel P, Chandrajith R, Gleixner G (2021). Mid-late Holocene sub-millennial scale inverse trends of South Asian summer and winter monsoons in Sri Lanka. Frontiers in Earth Science, 9: 789291: https://doi.org/10.3389/feart.2021.789291.'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Rajatheja MKJC, Chandrajith R, Bentota A, Jayasinghe GY (2021) A comparative assessment of trace element accumulation in native and improved rice (Oryza sativa L.) varieties grown under different conditions of fertilizer application. Biological Trace Element Research 199; 1153-1160. https://doi.org/10.1007/s12011-020-02213-9.'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Diyabalanage S, Kalpage MD, Mohotti DG,  Dissanayake CKK, Fernando R, Frew RD, Chandrajith R\r\n (2021) Comprehensive assessment of essential and potentially toxic trace elements in bovine milk and their feeds in different agro-climatic zones of Sri Lanka. Biological Trace element Research 199; 1377-1388. \r\n'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Senarathne S, Jayawardana JMCK, Edirisinghe EANV, Chandrajith R (2021) Influence of regional climatic on the hydrogeochemistry of a tropical river basin—a study from the Walawe river basin of Sri Lanka. Environmental Science and Pollution Research 28: 15701–15715.\r\n https://doi.org/10.1007/s11356-020-11712-0.\r\n'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Vithana CL, Ulapane PAK, Chandrajith R, Sullivan LA, Bundschuh J, Toppler N, Ward NJ, Senaratne, A (2021) Acid sulfate soils on the west coast of Sri Lanka: A review. Geoderma Regional 25: e00382. https://doi.org/10.1016/j.geodrs.2021.e00382.'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Koralegedara NH, Weedagama WLACI, Athurupana B, Balasooriya NWB, Chandrajith R, Senaratne A (2021) Chemical, Mineralogical and Textural Characterization of Red Earth Formation in the Northwest Coast of Sri Lanka. Journal of the Geological Society of Sri Lanka 22(1): 1-10.'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Wickramarathna S, Chandrajith R, Senaratne A, Paul V, Dash P, Wickramasinghe S, Biggs PJ (2021) Bacterial influence on the formation of hematite: implications for Martian dormant life. International Journal of Astrobiology 20(4): 270 - 284. http://doi.org/10.1017/S1473550421000124.'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Premaratne KM, Chandrajith R, Ratnayake NP (2021) An overview of Holocene monsoon variability of Sri Lanka and its association with Indian subcontinent climate records. Ceylon Journal of Science 50 (3); 207-218. http://doi.org/10.4038/cjs.v50i3.7901.'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Xu S, Li S-L, Yue F, Udeshani C, Chandrajith R (2021). Natural and Anthropogenic Controls of Groundwater Quality in Sri Lanka: Implications for Chronic Kidney Disease of Unknown Etiology (CKDu). Water 13(19): 2724. https://www.mdpi.com/2073-4441/13/19/2724'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Dushyantha NP, Ratnayake NP, Premasiri HMR, Ilankoon IMSK, Hemalal PVA, Jayawardena CL, Chandrajith R, Rohitha LPS, Abeysinghe AMKB, Dissanayake DMDOK, Dharmaratne PGR, Ratnayake AS, Batapola NM (2021) Leaching of Rare Earth Elements (REEs) from lake sediments around Eppawala phosphate deposit, Sri Lanka: A secondary source for REEs. Hydrometallurgy 205: 105751.\r\n https://doi.org/10.1016/j.hydromet.2021.105751.\r\n'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Pry, JM, Jackson W, Rupasinghe R, Lishanthe G, Badurdeen Z, Abeysekara T, Chandrajith R, Smith W, Wickramasinghe S (2021) A pilot case-control study using a one health approach to evaluate behavioral, environmental, and occupational risk factors for chronic kidney disease of unknown etiology in Sri Lanka. One Health Outlook 3(1):1-12. https://doi.org/10.1186/s42522-020-00034-3.\r\n\r\n'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Thillan K, Lanerolle P, Thoradeniya T, Samaranayake D, Chandrajith R, Wickramasinghe P (2021) Micronutrient status and associated factors of adiposity in primary school children with normal and high body fat in Colombo municipal area, Sri Lanka. BMC Paediatrics 21: 14. https://doi.org/10.1186/s12887-020-02473-3.'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Weerakoon WAP, Joshi H, Aggarwal N, Jha N, Jayasena HAH, Yakandawala, D, Chandrajith R, Ratnayake NP, Tiwari P (2021) Late Jurassic-Early Cretaceous palynostratigraphy and palaeoclimate in the Andigama Basin, Sri Lanka. Journal of Asian Earth Sciences X-6, 100067. https://doi.org/10.1016/j.jaesx.2021.100067.'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Rubasinghe RT, Gunatilake SK, Chandrajith R (2021) Climatic control of major and trace elements in paddy soils from wet and dry regions of Sri Lanka. Environmental Challenges 5: 100361. https://doi.org/10.1016/j.envc.2021.100361.\r\n\r\n'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Vlahos P, Schensul SL, Anand S, Emma Shipley E, Diyabalanage S, Hu C, Ha T, Staniec A, Haider L, Schensul JJ, Hewavitharane P, Silva T, Chandrajith R, Nanayakkara N (2021) Water sources and kidney function: investigating chronic kidney disease of unknown etiology in a prospective study. npj Clean Water 4, 50 (2021). https://doi.org/10.1038/s41545-021-00141-2.'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Chandrajith R (2021). Paddy farming, fertilizer, and chronic kidney disease with an undetermined origin. Ceylon Journal of Science, 50(4), 421–422. (Editorial) http://doi.org/10.4038/cjs.v50i4.7940'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Liyanage DND, Diyabalanage S, Dunuweera SP, Rajapakse S, Rajapakse RMG, Chandrajith R (2022) Significance of Mg-hardness and fluoride in drinking water on chronic kidney disease of unknown etiology in Monaragala, Sri Lanka. Environmental Research 203: 111779. https://doi.org/10.1016/j.envres.2021.111779'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Kalpage M, Dissanayake C, Diyabalanage S, Chandrajith R, Frew R, Fernando R (2022): Stable Isotope and Element Profiling for Determining the Agroclimatic Origin of Cow Milk within a Tropical Country. Foods 11, 275. https://doi.org/10.3390/foods11030275'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Jayasoma K, Koralegedara NH, Dharmapala A, Chandrajith R (2022): Microstructural and Geochemical Characterization of Gallstones: Implication for Biomineralization. Biological Trace Element Research 200: 4891-4902. https://doi.org/10.1007/s12011-021-03076-4.'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Chandrajith R, Bhagya S, Diyabalanage S, Wimalasiri S, Ranatunga MAB, Barth JAC (2022) Exposure Assessment of Fluoride Intake Through Commercially Available Black Tea (Camellia sinensis L.) from Areas with High Incidences of Chronic Kidney Disease with Undetermined Origin (CKDu) in Sri Lanka. Biological Trace Element Research 200; 526-234. https://doi.org/10.1007/s12011-021-02694-2.'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Karunanidhi D, Aravinthasamy P, Subramani T, Chandrajith R, Janardhana Raju N, Antunes IMHR. (2022) Provincial and seasonal influences on heavy metals in the Noyyal River of South India and their human health hazards. Environmental Research, 204: 111998. \r\nhttps://doi.org/10.1016/j.envres.2021.111998.\r\n'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Shipley ER, Vlahos P, Chandrajith R, Wijerathna P (2022) Agrochemical exposure in Sri Lankan inland water systems. Environmental Advances 7, 100150. https://doi.org/10.1016/j.envadv.2021.100150.\r\n\r\n'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Rupasinghe R, Amarasena S, Wickramarathna S, Biggs PJ, Chandrajith R, Wickramasinghe S (2022) Microbial diversity and ecology of geothermal springs in the high-grade metamorphic terrain of Sri Lanka. Environmental Advances 7: 100166. https://doi.org/10.1016/j.envadv.2022.100166.'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Medagedara A, Hewavitharane P, Chandrajith R, Abeysundara HK, Thatil R, Thennakoon S, Mahanama B, Weerasuriya N, Thilakarathne A, Nanayakkara N (2022). Comparison of biochemical characteristics between an endemic and a nonendemic area for CKDu Sri Lanka. Environmental Disease, 7(2), 47-51. https://doi.org/10.4103/ed.ed_3_22 '),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Suriyagoda LDB, Dissanayake O, Kodithuwakku V, Maduwanthi I, Dissanayaka N, Chandrajith R (2022). Accumulation of essential mineral and toxic trace elements in crops and soils of vegetable cropping systems in central highlands of Sri Lanka. The Journal of Agricultural Science, 160(1-2), 86-97. https://doi.org/10.1017/S0021859622000156 '),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Balasooriya S, Diyabalanage S, Yatigammana SK, Ileperuma OA, Chandrajith R (2021) Major and trace elements in rice paddy soils in Sri Lanka with special emphasis on regions with endemic chronic kidney disease of undetermined origin. Environment Geochemistry and Health 44: 1841-1855. https://doi.org/10.1007/s10653-021-01036-4.'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Premarathne, S, Chandrajith, R, Nanayakkara, N, et al. (2021) Could Consumption of Trace Element–Contaminated Rice Be a Risk Factor for Acute Interstitial Nephritis with Uncertain Etiology in the Dry Zone of Sri Lanka? Biological Trace Element Research 200: 2597-2605. \r\nhttps://doi.org//10.1007/s12011-021-02880-2.\r\n\r\n'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Gulegoda CR, Dissanayake CB, Amarasekara DS, Wijeratne S, Premadasa JK, Chandrajith R, Udagama PV (2022): Impact of Fluoride Exposure on Male Reproductive Parameters: A Pilot Case-Control Study in Sri Lanka. Exposure and Health 14: 447-457. https://doi.org/10.1007/s12403-022-00465-5.\r\n\r\n'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Chandrajith R, Diyabalanage S, (2022) Geo-environmental assessment of geochemistry of groundwater and associated human health risks in the dry zone terrain of Sri Lanka. Journal of National Science Foundation of Sri Lanka 50 (Special Issue); 213–229. http://doi.org/10.4038/jnsfsr.v50i0.11239.\r\n\r\n'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Jayatissa T, Ralapanawa U, Chandrajith R, Karunathilake P (2022) Variation of Serum Trace Element Levels in Patients with Hypertension, Acute Coronary Syndrome and Heart Failure: A Pilot Study. Sri Lanka Journal of Medicine, 31(1), pp.11–27. http://doi.org/10.4038/sljm.v31i1.301'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Vithana CL, Ulapane PAK, Chandrajith R, Sullivan LA, Bundschuh J, Toppler N, Ward N, Senaratne A. (2022) Assessment of the acidification risk of the acid sulfate soil materials in a tropical coastal peat bog: Muthurajawela Marsh, Sri Lanka. CATENA, 216, 106396. https://doi.org/10.1016/j.catena.2022.106396 \r\n\r\n'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Senarathne S, Jayawardana JMCK, Chandrajith R (2022) Influence of climate on groundwater fluoride in different climatic domains in a hard rock terrain of Sri Lanka: implications to community health. Environ Geochem Health 44, 3677–3686. https://doi.org/10.1007/s10653-021-01090-y'),
(NULL, 'Prof.R.L.R.Chandrajith', 'Science', 'Udeshani WC, Koralegedara NH, Gunatilake SK, Li SL, Zhu X, Chandrajith R. (2022) Geochemistry of Groundwater in the Semi-Arid Crystalline Terrain of Sri Lanka and Its Health Implications among Agricultural Communities. Water 14(20):3241. https://doi.org/10.3390/w14203241\r\n\r\n'),
(NULL, 'Dr.M.H.F.Sakeena', 'Allied Health Sciences', 'Sakeena MHF, Bennett AA, McLachlan AJ. Investigating knowledge regarding antibiotics and antimicrobial resistance among pharmacy students in Australian universities. Journal of Pharmacy Practice and Research 2020, 50 (5).'),
(NULL, 'Dr.M.H.F.Sakeena', 'Allied Health Sciences', 'Sakeena MHF, Bennett AA, McLachlan AJ. Strategies to be implemented in Sri Lanka to overcome the challenge of antimicrobial resistance:  Narrative review.  Pharmaceutical Journal of Sri Lanka 2020; 10 (1), 1-11.'),
(NULL, 'Dr.A.C.M.Fahim', 'Allied Health Sciences', 'Deb Prasad Pandey, Bhola Ram Shrestha, Krishna Prasad Acharya, Khagendra Jang Shah, Chhabilal Thapa-Magar, Ishwari Prasad Dhakal, Fahim Mohamed, Geoffrey K Isbister, A prospective study of snakebite in a tertiary care hospital in south-western Nepal, Transactions of The Royal Society of Tropical Medicine and Hygiene, 2023;, trac127, https://doi.org/10.1093/trstmh/trac127'),
(NULL, 'Dr.A.C.M.Fahim', 'Allied Health Sciences', 'Qiang S, Mohamed F, Mackenzie L, Roberts MS. Rapid determination of polyethoxylated tallow amine surfactants in human plasma by LC-MSMS. Talanta. 2022 Nov 19;254:124115. doi: 10.1016/j.talanta.2022.124115. Epub ahead of print. PMID: 36481395.'),
(NULL, 'Dr.A.C.M.Fahim', 'Allied Health Sciences', 'Wijerathna TM, Buckley NA, Gawarammana IB, Raubenheimer J, Shahmy S, Chathuranga U, Palangasinghe C, Shihana F, Mohamed F. Epidemiology and renal injury following 2-methyl-4-chlorophenoxyacetic acid (MCPA) poisoning. Sci Rep. 2022 Dec 19;12(1):21940. doi: 10.1038/s41598-022-25313-z. PMID: 36535986; PMCID: PMC9763389.'),
(NULL, 'Dr.A.C.M.Fahim', 'Allied Health Sciences', 'Deuster E, Tomenson JA, Mohamed F, Gawarammana I, Buckley NA, Wilks MF, Eddleston M. Dose ingested, vomiting, and outcome in patients ingesting a standard paraquat 20SL formulation. Clin Toxicol (Phila). 2022 Dec 21:1-10. doi: 10.1080/15563650.2022.2142601. Epub ahead of print. PMID: 36541442.'),
(NULL, 'Dr.A.C.M.Fahim', 'Allied Health Sciences', 'Dhanarisi J, Perera S, Wijertahna T, Gawarammana I, Eddleston M, Mohamed F. Relationship between alcohol co-ingestion and clinical outcome in pesticide self-poisoning: a systematic review and a meta-analysis. Alcohol and Alcoholism, 2022;, agac045, https://doi.org/10.1093/alcalc/agac045'),
(NULL, 'Dr.A.C.M.Fahim', 'Allied Health Sciences', 'Edward Nendick, Mohamed F, Jacques Raubenheimer, Indika Gawarammana, Nick A. Buckley & Michael Eddleston (2022) Acute fungicide self-poisoning - a prospective case series, Clinical Toxicology, DOI: 10.1080/15563650.2022.2105710'),
(NULL, 'Dr.A.C.M.Fahim', 'Allied Health Sciences', 'Schölin L, Weerasinghe M, Agampodi S,  Chathurange U, Rajapaksha S, Holloway A, Norrie J, Mohamed F, Eddleston M, Pearson M. (March 2022) Involvement of alcohol in injury cases in rural Sri Lanka: prevalence and associated factors among in-patients in three primary care hospitals. BMC Public Health, 22(1)'),
(NULL, 'Dr.A.C.M.Fahim', 'Allied Health Sciences', 'Wijewickrama ES, Mohamed F, Gawarammana IB, Endre ZH, Buckley NA, Isbister GK. (2021, December 6).Serum and urinary biomarkers for early detection of acute kidney injury following Hypnale spp. envenoming. PLOS Neglected Tropical Diseases, 15(12), e0010011. doi: 10.1371/journal.pntd.0010011.'),
(NULL, 'Dr.A.C.M.Fahim', 'Allied Health Sciences', 'Dhanarisi J, Tzotzolaki TM, Vasileva AD, Kjellberg MA, Hakulinen H, Vanninen P, Gawarammana I, Mohamed F, Hovda KE, Eddleston M. (2021, November 18). Osmolal and anion gaps after acute self-poisoning with agricultural formulations of the organophosphorus insecticides profenofos and diazinon - a pilot study. Basic clinical pharmacology & toxicology, 130(2), 320-327. doi: 10.1111/bcpt.13686.'),
(NULL, 'Dr.A.C.M.Fahim', 'Allied Health Sciences', 'Pett J, Mohamed F, Knight J, Linhart C, Osborne NJ, Taylor R. (2021, October 26). Two decades of Chronic Kidney Disease of Unknown Aetiology research: Existing evidence and persistent gaps from epidemiological studies in Sri Lanka. Nephrology, 27(3), 238-247. doi:10.1111/nep.13989.'),
(NULL, 'Dr.A.C.M.Fahim', 'Allied Health Sciences', 'Prasadi GAM, , Senarathna L , Dharmaratne SD, Mohamed F, Jayasinghe S, Dawson A. (2021, November 1). Mother’s ability to determine and measure paracetamol doses for children-a contrived observational study. Journal of Child Health Care. https://doi.org/10.1177/13674935211046101'),
(NULL, 'Dr.A.C.M.Fahim', 'Allied Health Sciences', 'Perananthan V, Wijerathna T, Mohamed F, Gawarammana I, Dawson A, Buckley N. (2021, August 11). Circulating intestinal fatty acid binding protein and gastrointestinal toxicity in Russell’s Viper envenomation. Clinical Toxicology (Philadelphia, Pa.), 60(3), 311–318. DOI:10.1080/15563650.2021.1965160'),
(NULL, 'Dr.A.C.M.Fahim', 'Allied Health Sciences', 'Rambabu L, Mohamed F, Dhanarisi J,  Gawarammana I, Raubenheimer J, Mackenzie L, Roberts MS, Buckley NA, Eddleston M. (2021, May 7). Acute phenthoate self-poisoning: a prospective case series. Clinical Toxicology, 60(2), 214-220. DOI: 10.1080/15563650.2021.1917596'),
(NULL, 'Dr.A.C.M.Fahim', 'Allied Health Sciences', 'Buckley NA, Mohamed F, Raubenheimer J,Gawarammana I, Eddleston M, Roberts MS, Dawson AH. (2021, June 1). Case fatality of agricultural pesticides after self-poisoning in Sri Lanka: a prospective cohort study. The Lancet Global Health, 9(6), E854-E862. https://doi.org/10.1016/ S2214-109X(21)00086-3.'),
(NULL, 'Dr.A.C.M.Fahim', 'Allied Health Sciences', 'Shihana F, Wong WKM, Joglekar MV, Mohamed F, Gawarammana I, Isbister K, Hardikar AA, Seth D, Buckley NA. (2021, April 28). Urinary microRNAs as non-invasive biomarkers for toxic acute kidney injury in humans. Scientific Reports 11, 9165 (2021). https://doi.org/10.1038/s41598-021-87918-0'),
(NULL, 'Dr.A.C.M.Fahim', 'Allied Health Sciences', 'Shihana F , Barron ML. Mohamed F, Seth D, Buckley NA. (2021, April). MicroRNA in toxic acute kidney injury: Systematic scoping review of the current status. Pharmacology Research & Perspectives, 9(2), e00695.  doi: 10.1002/prp2.695.'),
(NULL, 'Dr.A.C.M.Fahim', 'Allied Health Sciences', 'Wijerathna, T. M, Mohamed, F, Gawarammana, I.B, Wunnapuk, K, Dissanayake, D. M, Shihana, F, Buckley, N. A. (2020, November). Cellular injury leading to oxidative stress in acute poisoning with potassium permanganate/oxalic acid, paraquat, and glyphosate surfactant herbicide. Environmental toxicology and pharmacology, 80, 103510.  https://doi.org/10.1016/j.etap.2020.103510'),
(NULL, 'Dr.A.C.M.Fahim', 'Allied Health Sciences', 'Shihana F , Mohamed F , Joglekar MV, Hardikar AA, Seth D, Buckley NA. (2020, November 1). Urinary versus serum microRNAs in human oxalic acid poisoning: Contrasting signals and performance. Toxicology Letters, 334, 21-26. https://doi.org/10.1016/j.toxlet.2020.09.003'),
(NULL, 'Dr.A.C.M.Fahim', 'Allied Health Sciences', 'Perananthan V, Mohamed F, Shahmy S, Gawarammana I, Dawson A, Buckley N. (2020, September 22). The clinical toxicity of imidacloprid self-poisoning following the introduction of newer formulations. Clinical Toxicology,59(4), 347-350. DOI: 10.1080/15563650.2020.1815760'),
(NULL, 'Dr.W.M.G.M.B.Bowatte', 'Allied Health Sciences', 'Tan DJ, Lodge CJ, Walters EH, Lowe AJ, Bui DS, Bowatte G, Kandane‐Rathnayake R, Aldakheel FM, Erbas B, Hamilton GS, Thomas PS. Biomarkers of asthma relapse and lung function decline in adults with spontaneous asthma remission: a population‐based cohort study. Allergy. Published online 2022 Oct 27. doi.org/10.1111/all.15566'),
(NULL, 'Dr.W.M.G.M.B.Bowatte', 'Allied Health Sciences', 'Dharmage SC, Bui DS, Walters EH, Lowe AJ, Thompson B, Bowatte G, Thomas P, Garcia-Aymerich J, Jarvis D, Hamilton GS, Johns DP. Lifetime spirometry patterns of obstruction andrestriction, and their risk factors and outcomes: a prospective cohort study. The Lancet Respiratory Medicine. Published online 2022 Oct 14. doi.org/10.1016/S2213-2600(22)00364-2'),
(NULL, 'Dr.W.M.G.M.B.Bowatte', 'Allied Health Sciences', 'Tandra M, Walters EH, Perret J, Lowe AJ, Lodge CJ, Johns DP, Thomas PS, Bowatte G, Davis PG, Abramson MJ, Dharmage SC. Small for gestational age is associated with reduced lung function in middle age: A prospective study from first to fifth decade of life. Respirology. 28(2), 159-165.'),
(NULL, 'Dr.W.M.G.M.B.Bowatte', 'Allied Health Sciences', 'Senarathna M, Priyankara S, Jayaratne R, Weerasooriya R, Morawska L, Bowatte G. Measuring Traffic Related Air Pollution Using Smart Sensors In Sri Lanka: Before And During A New Traffic Plan. Geography, Environment, Sustainability. 2022 Oct 4;15(3):27-36.'),
(NULL, 'Dr.W.M.G.M.B.Bowatte', 'Allied Health Sciences', 'Liu J, Bowatte G, Pham J, Perret JL, Holloway JW, Lowe AJ, Burgess JA, Svanes C, Thomas P, Russell MA, Erbas B. Pre-pubertal smoke exposure of fathers and increased risk of offspring asthma: a possible transgenerational effect. European Respiratory Journal. 2022 Oct 1;60(4).'),
(NULL, 'Dr.W.M.G.M.B.Bowatte', 'Allied Health Sciences', 'Senanayake U, Bowatte G. Effects of Human Milk Oligosaccharides on Microbiome. Sri Lankan Journal of Health Sciences. 2022 Jul 6;1(1).'),
(NULL, 'Dr.W.M.G.M.B.Bowatte', 'Allied Health Sciences', 'Dayarathana K, Sakeena MH, Bowatte G. Use and Attitudes of Complementary and Alternative Medicines Among Allied Health Sciences Students, University of Peradeniya. Sri Lankan Journal of Health Sciences. 2022 Jul 6;1(1).'),
(NULL, 'Dr.W.M.G.M.B.Bowatte', 'Allied Health Sciences', 'Perret JL, Wurzel D, Walters EH, Lowe AJ, Lodge CJ, Bui DS, Erbas B, Bowatte G, Russell MA, Thompson BR, Gurrin L. Childhood ‘bronchitis’ and respiratory outcomes in middle-age: a prospective cohort study from age 7 to 53 years. BMJ open respiratory research. 2022 Jun 1;9(1): e001212.'),
(NULL, 'Dr.W.M.G.M.B.Bowatte', 'Allied Health Sciences', 'Bui DS, Perret JL, Walters EH, Lodge CJ, Bowatte G, Hamilton GS, Thompson BR, Frith P, Erbas B, Thomas PS, Johns DP. Association between very to moderate preterm births, lung function deficits, and COPD at age 53 years: analysis of a prospective cohort study. The Lancet Respiratory Medicine. 2022 May 1;10(5):478-84.'),
(NULL, 'Dr.W.M.G.M.B.Bowatte', 'Allied Health Sciences', 'Lall O, Bowatte G, Dharmaratne S, Lowe AJ, Vakalopoulos A, Ambrose I, Jayasinghe P, Yasaratne D, Heyworth J, Dharmage SC. Household use of biomass fuel, especially traditional stove is associated with childhood wheeze and eczema: a cross sectional study of rural communities in Kandy, Sri Lanka. Journal of Asthma. 2022 Feb 17:1-9.'),
(NULL, 'Dr.W.M.G.M.B.Bowatte', 'Allied Health Sciences', 'Bowatte G, Bui DS, Priyankara S, Lowe AJ, Perret JL, Lodge CJ, Hamilton GS, Erbas B, Thomas P, Thompson B, Schlünssen V. Parental preconception BMI trajectories from childhood to adolescence and asthma in the future offspring. Journal of Allergy and Clinical Immunology. 2022; 150(1):67-74.'),
(NULL, 'Dr.W.M.G.M.B.Bowatte', 'Allied Health Sciences', 'Ali GB, Lowe AJ, Perret JL, Walters EH, Lodge CJ, Johns D, James A, Erbas B, Hamilton GS, Bowatte G, Wood-Baker R. Impact of lifetime body mass index trajectories on the incidence and persistence of adult asthma. European Respiratory Journal. 2022; 60(3).'),
(NULL, 'Dr.W.M.G.M.B.Bowatte', 'Allied Health Sciences', 'Bui D, Lodge C, Perret J, Lowe A, Hamilton G, Thompson B, Giles G, Tan D, Erbas B, Pirkis J, Cicuttini F, Cassim R, Bowatte G, Thomas P, Garcia Aymerich J, Hopper J, Abramson M, Walters E, Dharmage SC. Trajectories of asthma and allergies from 7 years to 53 years and associations with lung function and extrapulmonary comorbidity profiles: a prospective cohort study. The Lancet Respiratory Medicine. 2021;9(4):387-96.'),
(NULL, 'Dr.W.M.G.M.B.Bowatte', 'Allied Health Sciences', 'Bui DS, Agusti A, Walters H, Lodge C, Perret JL, Lowe A, Bowatte G, Cassim R, Hamilton GS, Frith P, James A, Thomas PS, Jarvis D, Abramson MJ, Faner R, Dharmage SC. Lung function trajectory and biomarkers in the Tasmanian Longitudinal Health Study. ERJ Open Res. 2021;7(3).'),
(NULL, 'Dr.W.M.G.M.B.Bowatte', 'Allied Health Sciences', 'Dai X, Bui D, Perret J, Lowe A, Frith P, Bowatte G, Thomas P, Giles G, Hamilton G, Tsimiklis H, Hui J, Burgess J, Win A, Abramson M, Walters EH, Dharmage S, Lodge C. Exposure to household air pollution over 10 years is related to asthma and lung function decline. European Respiratory Journal. 2021;57(1).'),
(NULL, 'Dr.W.M.G.M.B.Bowatte', 'Allied Health Sciences', 'Kaushalya L, Bowatte G, Yasaratne D. Post COVID-19: A narrative review of a new challenge. Sri Lanka Journal of Medicine. 2021; 30:30(2).'),
(NULL, 'Dr.W.M.G.M.B.Bowatte', 'Allied Health Sciences', 'Lodge, Lodge C, Lowe A, Milanzi E, Bowatte G, Abramson M, Tsimiklis H, Axelrad C, Robertson B, Darling A, Svanes C, Wjst M, Dharmage S, Bode L. Human milk oligosaccharide profiles and allergic disease up to 18 years. Journal of allergy and clinical immunology. 2021;147(3):1041-8.'),
(NULL, 'Dr.W.M.G.M.B.Bowatte', 'Allied Health Sciences', 'Lopez, Lopez D, Lodge C, Bui D, Waidyatillake N, Su J, Perret J, Knibbs L, Erbas B, Thomas P, Hamilton G, Thompson B, Abramson M, Walters EH, Dharmage S, Bowatte G, Lowe AJ. Association between ambient air pollution and development and persistence of atopic and non‐atopic eczema in a cohort of adults. Allergy. 2021; 76(8):2524-34.'),
(NULL, 'Dr.W.M.G.M.B.Bowatte', 'Allied Health Sciences', 'Senarathna M, Jayaratne R, Morawska L, Guo Y, Knibbs LD, Bui D, Abeysundara S, Weerasooriya R, Bowatte G. Impact of COVID-19 lockdown on air quality of Sri Lankan cities. International Journal of Environmental Pollution and Remediation. 2021;9:12-21.'),
(NULL, 'Dr.W.M.G.M.B.Bowatte', 'Allied Health Sciences', 'Priyankara S, Senarathna M, Jayaratne R, Morawska L, Abeysundara S, Weerasooriya R, Knibbs LD, Dharmage SC, Yasaratne D, Bowatte G. Ambient PM(2.5) and PM(10) Exposure and Respiratory Disease Hospitalization in Kandy, Sri Lanka. Int J Environ Res Public Health. 2021;18(18).'),
(NULL, 'Dr.W.M.G.M.B.Bowatte', 'Allied Health Sciences', 'Song Y, Walters EH, Abramson MJ, Bowatte G, Bui DS, Perret J, Feather I, Knibbs LD, Wilson R, Nichols DS, Dharmage SC, Zosky GR. Protein levels, air pollution and vitamin D deficiency: links with allergy. ERJ Open Res. 2021;7(4).'),
(NULL, 'Dr.W.M.G.M.B.Bowatte', 'Allied Health Sciences', 'Tan, Tan D, Lodge C, Lowe A, Bui D, Bowatte G, Johns D, Hamilton G, Thomas P, Abramson M, Walters EH, Perret J, Dharmage SC. Bronchodilator reversibility as a diagnostic test for adult asthma: findings from the population-based Tasmanian Longitudinal Health Study. ERJ Open Research. 2021;7(1):00042.'),
(NULL, 'Dr.W.M.G.M.B.Bowatte', 'Allied Health Sciences', 'Triebner K, Bui D, Walters EH, Abramson MJ, Bowatte G, Campbell B, Dadvand P, Erbas B, Johns DP, Leynaert B, Lodge CJ, Lowe AJ, Perret JL, Hustad S, Gómez Real F, Dharmage SC. Childhood lung function as a determinant of menopause-dependent lung function decline. Maturitas. 2021;153:41-7.'),
(NULL, 'Dr.W.M.G.M.B.Bowatte', 'Allied Health Sciences', 'Vakalopoulos, Vakalopoulos A, Dharmage S, Dharmaratne S, Jayasinghe P, Lall O, Ambrose I, Weerasooriya R, Bui D, Yasaratne D, Heyworth J, Bowatte G. Household Air Pollution from Biomass Fuel for Cooking and Adverse Fetal Growth Outcomes in Rural Sri Lanka. International Journal of Environmental Research and Public Health. 2021;18(4):1878.'),
(NULL, 'Dr.W.M.G.M.B.Bowatte', 'Allied Health Sciences', 'Zeng, Zeng X, Lodge C, Lowe A, Guo Y, Abramson M, Bowatte G, Hu L, Yang B, Chen Z, Dharmage S, Dong GH. Current pet ownership modifies the adverse association between long‐term ambient air pollution exposure and childhood asthma. Clinical and Translational Allergy. 2021;11(1):e12005.'),
(NULL, 'Dr.W.M.G.M.B.Bowatte', 'Allied Health Sciences', 'Bui DS, Lodge CJ, Perret JL, Lowe A, Hamilton GS, Thompson B, Giles G, Tan D, Erbas B, Pirkis J, Cicuttini F. Cassim R, Bowatte G, Thomas P, Garcia-Aymerich J, Hopper J, Abramson MJ, Walters EH, Dharmage SC. Trajectories of asthma and allergies from 7 years to 53 years and associations with lung function and extrapulmonary comorbidity profiles: a prospective cohort study. The Lancet Respiratory Medicine. 2020 Nov 17.'),
(NULL, 'Dr.W.M.G.M.B.Bowatte', 'Allied Health Sciences', 'Peralta GP, Marcon A, Carsin AE, Abramson MJ, Accordini S, Amaral AF, Antó JM, Bowatte G, Burney P, Corsico A, Demoly P. Body mass index and weight change are associated with adult lung function trajectories: the prospective ECRHS study. Thorax. 2020 Apr 1;75(4):313-20.'),
(NULL, 'Dr.W.M.G.M.B.Bowatte', 'Allied Health Sciences', 'Campbell B, Simpson JA, Bui DS, Lodge CJ, Lowe AJ, Matheson MC, Bowatte G, Burgess JA, Hamilton GS, Leynaert B, Gómez Real F. Early menarche is associated with lower adult lung function: A longitudinal cohort study from the first to sixth decade of life. Respirology. 2020 Mar;25(3):289-97.'),
(NULL, 'Dr.W.M.G.M.B.Bowatte', 'Allied Health Sciences', 'Bui DS, Perret JL, Walters EH, Abramson MJ, Burgess JA, Bui MQ, Bowatte G, Lowe AJ, Russell MA, Alif SM, Thompson BR. Lifetime Risk Factors for Pre-and Post-Bronchodilator Lung Function Decline. A Population-based Study. Annals of the American Thoracic Society. 2020 Mar;17(3):302-12.'),
(NULL, 'Dr.W.M.G.M.B.Bowatte', 'Allied Health Sciences', 'Harun NS, Lachapelle P, Bowatte G, Lodge C, Braitberg G, Irving L, Hinks T, Dharmage S, Douglass J. 2016 Thunderstorm-asthma epidemic in Melbourne, Australia: An analysis of patient characteristics associated with hospitalization. Canadian Journal of Respiratory, Critical Care, and Sleep Medicine. 2020 Mar 11:1-7.'),
(NULL, 'Dr.W.M.G.M.B.Bowatte', 'Allied Health Sciences', 'Campbell B, Bui DS, Simpson JA, Lodge CJ, Lowe AJ, Bowatte G, Leynaert B, Real FG, Thomas PS, Giles GG, Johns DP. Early Age at Natural Menopause Is Related to Lower Post-Bronchodilator Lung Function. A Longitudinal Population-based Study. Annals of the American Thoracic Society. 2020 Apr;17(4):429-37.'),
(NULL, 'Dr.W.M.G.M.B.Bowatte', 'Allied Health Sciences', 'Dai X, Bui D, Perret JL, Lowe A, Frith PA, Bowatte G, Thomas P, Giles GG, Hamilton GS, Tsimiklis H, Hui J, Burgess J, Win A, Abramson M, Walters H, Dharmage S, Lodge C. Exposure to household air pollution over 10 years is related to asthma and lung function decline. The European Respiratory Journal. 2020; 1;57(1).'),
(NULL, 'Dr.W.M.G.M.B.Bowatte', 'Allied Health Sciences', 'Lodge CJ, Lowe AJ, Milanzi E, Bowatte G, Abramson MJ, Tsimiklis H, Axelrad C, Robertson B, Darling AE, Svanes C, Wjst M. Human milk oligosaccharide profiles and allergic disease up to 18 years. Journal of Allergy and Clinical Immunology. 2020; 147(3):1041-8.'),
(NULL, 'Dr.W.M.G.M.B.Bowatte', 'Allied Health Sciences', 'Clark DP, Son DB, Bowatte G, Senaratna CV, Lodge C, Perret JL, Hamilton GS, Dharmage S. The association between traffic-related air pollution and obstructive sleep apnea: A systematic review. Sleep Medicine Reviews. 2020 Jul 11:101360.'),
(NULL, 'Prof.P.P.A.W.Athukorala', 'Arts', '2023	Wickramasinghe, M.A.,  Athukorala, W.,  Senarathne, G.J. and  P. R. D. Yapa. (2022).  Examine the Reliability of Econometrics Software: An Empirical Comparison of Time Series Modelling, Open Journal of Statistics, 13 (1): DOI: 10.4236/ojs.2023.131003. \r\n\r\n'),
(NULL, 'Prof.P.P.A.W.Athukorala', 'Arts', '2022	Athukorala, W., Wilson, C., Lee, B. and S. Managi. (2022). Measuring the impact of Pesticide exposure on farmers’ health and farm productivity, Economic Analysis and Policy, 77: 851-862. \r\n\r\n'),
(NULL, 'Prof.P.P.A.W.Athukorala', 'Arts', 'Athukorala, W., Gangahagedara, R., Bandara, S. Y., Ratwatte, V., Karunarathna, M. and S. Subasinghe. (2022). Transformation of agricultural practices and health outcomes: An empirical investigation of Chronic Kidney Disease of unknown Etiology (CKDu) in Sri Lanka. Annals of Bioethics and Clinical Application, 5(1): 000221. DOI: 10.23880/abca-16000221. '),
(NULL, 'Prof.P.P.A.W.Athukorala', 'Arts', 'Athukorala, W., Karunarathna, M. and S. Y. Bandara. (2022). Estimating health impacts of pesticides use: New evidence from vegetable farmers in Sri Lanka. Biomedical Journal of Scientific & Technical Research, 41(2). BJSTR. MS.ID.006565. '),
(NULL, 'Prof.P.P.A.W.Athukorala', 'Arts', 'Gangahagedara, R., Karunarathna, M., Athukorala, W., Subasinghe, S. and P. Ekanayake. (2021). Emergency Teaching–Learning Methods (ETLM) during COVID-19: Lessons learned from Sri Lanka. Education Sciences, 11(10): 579'),
(NULL, 'Prof.P.P.A.W.Athukorala', 'Arts', '2021	Gangahagedara, R., Subasinghe, S., Lankathilake, M., Athukorala, W. and I. Gamage. (2021). Ecosystem services research trends: A bibliometric analysis from 2000-2020. Ecologies, 2(4): 266-379. https://doi.org/10.3390/ecologies2040021. \r\n\r\n'),
(NULL, 'Prof.P.P.A.W.Athukorala', 'Arts', '2020	Wilson, C., Athukorala, W., Torgler, B., Gifford, R., Garcia-Valiñas, M.A. and S. Managi. (2020). Willingness to pay to ensure a continuous water supply with minimum restrictions. Empirical Economics, 61:1519-1537. \r\n\r\n'),
(NULL, 'Prof.P.P.A.W.Athukorala', 'Arts', 'Athukorala, W., Karunarathna, M., Wilson, C. and S. Managi. (2020). Conservation of genetic resources of crops: farmer preferences for banana diversity in Sri Lanka. Journal of Forest Economics, 35 (2-3): 177-206. ');

-- --------------------------------------------------------

--
-- Table structure for table `researchers`
--

CREATE TABLE `researchers` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `faculty` varchar(50) DEFAULT NULL,
  `URL` text DEFAULT '../../img/researchers/avatar.jpg'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `researchers`
--

INSERT INTO `researchers` (`id`, `name`, `faculty`, `URL`) VALUES
(1, 'Prof.D.N.B.Gunawardane', 'Arts', '../../img/researchers/DNBGunewardena.jpg'),
(2, 'Dr.S.A.H.A.Suraweera', 'Engineering', '../../img/researchers/avatar.jpg'),
(4, 'Prof.K.M.S.Wimalasiri', 'Agriculture', '../../img/researchers/avatar.jpg'),
(5, ' Prof.W.M.TMadujith', 'Agriculture', '../../img/researchers/avatar.jpg\r\n'),
(6, 'Prof.B.Marambe', 'Agriculture', '../../img/researchers/avatar.jpg\r\n'),
(7, 'Prof.M.I.M.Mowjood', 'Agriculture', '../../img/researchers/avatar.jpg\r\n'),
(8, 'Prof.S.P.Nissanka', 'Agriculture', '../../img/researchers/avatar.jpg\r\n'),
(9, 'Prof.B.M.L.D.B.Sooriyagoda', 'Agriculture', '../../img/researchers/avatar.jpg\r\n'),
(11, 'Dr.B.E.P.Mendis', 'Agriculture', '../../img/researchers/avatar.jpg\r\n'),
(12, 'Dr.R.P.N.P.Rajapakse', 'Agriculture', '../../img/researchers/avatar.jpg\r\n'),
(14, 'Dr.W.M.G.M.B.Bowatte', 'Allied Health Sciences', '../../img/researchers/WMGMBBowatte.jpg\r\n'),
(15, 'Dr.A.C.M.Fahim', 'Allied Health Sciences', '../../img/researchers/ACMFahim.jpg'),
(16, 'Dr.M.H.F.Sakeena', 'Allied Health Sciences', '../../img/researchers/MHFSakeena.jpg'),
(17, 'Prof.S.L.Ekanayake', 'Dental Sciences', '../../img/researchers/avatar.jpg'),
(18, 'Prof.W.M.Thilakarathne', 'Dental Sciences', '../../img/researchers/WMThilakarathne.jpg'),
(19, 'Prof.M.A.R.M.Fernando', 'Engineering', '../../img/researchers/MARMFernando.jpg'),
(20, 'Prof.K.B.S.N.Jinadasa', 'Engineering', '../../img/researchers/KBSNJinadasa.jpg'),
(21, 'Prof.R.G.Ragel', 'Engineering', '../../img/researchers/RRagel.jpg'),
(22, 'Prof.S.D.Dharmarathne', 'Medicine', '../../img/researchers/avatar.jpg'),
(23, 'Prof.N.S.Kalupahana', 'Medicine', '../../img/researchers/avatar.jpg'),
(24, 'Prof.M.K.Prasad', 'Medicine', '../../img/researchers/avatar.jpg'),
(25, 'Prof.R.L.R.Chandrajith', 'Science', '../../img/researchers/RLRChandrajith.jpg'),
(26, 'Prof.D.N.Karunarathne', 'Science', '../../img/researchers/avatar.jpg'),
(27, 'Prof.N.L.V.V.Karunarathne', 'Science', '../../img/researchers/avatar.jpg'),
(28, 'Prof.A.D.L.C.Perera', 'Science', '../../img/researchers/ADLCPerera.png'),
(29, 'Prof.H.M.D.N.Priyantha', 'Science', '../../img/researchers/avatar.jpg'),
(30, 'Prof.R.S.Rajakaruna', 'Science', '../../img/researchers/RSRajakaruna.jpg'),
(31, 'Prof.R.P.V.J.Rajapakse', 'Veterinary Medicine and Animal Sciences', '../../img/researchers/avatar.jpg'),
(32, 'Prof.J.B.Ekanayake', 'Engineering', '../../img/researchers/JBEknayake.jpg'),
(33, 'Dr.A.D.Igalavithana', 'Agriculture', '../../img/researchers/ADIgalavithana.jpg'),
(34, 'Dr.K.W.L.K.Weerasinghe', 'Agriculture', '../../img/researchers/KWLKWeerasinghe.png'),
(35, 'Prof.W.A.J.M.De Costa', 'Agriculture', '../../img/researchers/avatar.jpg'),
(36, 'Prof.K.A.S.S.Kodithuwakku', 'Agriculture', '../../img/researchers/avatar.jpg'),
(37, 'Prof.D.K.N.G.Pushpakumara', 'Agriculture', '../../img/researchers/avatar.jpg'),
(38, 'Prof.G.L.P.P.Silva', 'Agriculture', '../../img/researchers/avatar.jpg'),
(39, 'Prof.J.K.Vidanarachchi', 'Agriculture', '../../img/researchers/avatar.jpg'),
(40, 'Prof.U.W.A.Vitharana', 'Agriculture', '../../img/researchers/avatar.jpg'),
(41, 'Prof.H.L.J.Weerahewa', 'Agriculture', '../../img/researchers/avatar.jpg'),
(42, 'Prof.B.C.Jayawardana', 'Agriculture', '../../img/researchers/avatar.jpg'),
(43, 'Prof.T.M.W.J.Bandara', 'Science', '../../img/researchers/TMWJBandara.jpg'),
(44, 'Prof.M.A.S.P.K.Malaviarachchi', 'Science', '../../img/researchers/MASPKMalaviarachchi.png'),
(45, 'Prof.R.M.G.Rajapakse', 'Science', '../../img/researchers/avatar.jpg'),
(46, 'Prof.P.Samarasekara', 'Science', '../../img/researchers/PSamarasekara.jpg'),
(47, 'Prof.I.B.Gawarammana', 'Medicine', '../../img/researchers/avatar.jpg'),
(48, 'Prof.S.A.M.Kularatne', 'Medicine', '../../img/researchers/avatar.jpg'),
(49, 'Dr.U.J.M.A.L.Jayasinghe', 'Allied Health Sciences', '../../img/researchers/avatar.jpg'),
(50, 'Dr.A.N.Madusanka ', 'Engineering', '../../img/researchers/avatar.jpg'),
(52, 'Prof.S.J.S.De mel', 'Arts', '../../img/researchers/avatar.jpg'),
(69, 'Prof.P.P.A.W.Athukorala', 'Arts', '../../img/researchers/Wasantha Athukorala.jpg');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `pubnew`
--
ALTER TABLE `pubnew`
  ADD UNIQUE KEY `id` (`id`);

--
-- Indexes for table `researchers`
--
ALTER TABLE `researchers`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `researchers`
--
ALTER TABLE `researchers`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=70;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
